#! /bin/bash

python ./BuildLangModel.py ar  
python ./BuildLangModel.py be  
python ./BuildLangModel.py bg  
python ./BuildLangModel.py ca  
python ./BuildLangModel.py cs  
python ./BuildLangModel.py da  
python ./BuildLangModel.py de  
python ./BuildLangModel.py el  
python ./BuildLangModel.py en  
python ./BuildLangModel.py eo  
python ./BuildLangModel.py es  
python ./BuildLangModel.py et  
python ./BuildLangModel.py fi  
python ./BuildLangModel.py fr  
python ./BuildLangModel.py ga  
python ./BuildLangModel.py he  
python ./BuildLangModel.py hi  
python ./BuildLangModel.py hr  
python ./BuildLangModel.py hu  
python ./BuildLangModel.py it  
python ./BuildLangModel.py ka  
python ./BuildLangModel.py ko  
python ./BuildLangModel.py lt  
python ./BuildLangModel.py lv  
python ./BuildLangModel.py mk  
python ./BuildLangModel.py mt  
python ./BuildLangModel.py no  
python ./BuildLangModel.py pl  
python ./BuildLangModel.py pt  
python ./BuildLangModel.py ro  
python ./BuildLangModel.py ru  
python ./BuildLangModel.py sk  
python ./BuildLangModel.py sl  
python ./BuildLangModel.py sr  
python ./BuildLangModel.py sv  
python ./BuildLangModel.py th  
python ./BuildLangModel.py tr  
python ./BuildLangModel.py uk  
python ./BuildLangModel.py vi  
