
LANGUAGES =                 \
		ar					\
		be					\
		bg					\
		ca					\
		cs					\
		da					\
		de					\
		el					\
		en					\
		eo					\
		es					\
		et					\
		fi					\
		fr					\
		ga					\
		he					\
		hi					\
		hr					\
		hu					\
		it					\
		ka					\
		ko					\
		lt					\
		lv					\
		mk					\
		mt					\
		no					\
		pl					\
		pt					\
		ro					\
		ru					\
		sk					\
		sl					\
		sr					\
		sv					\
		th					\
		tr					\
		uk					\
		vi

all: all_languages

# https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html
all_languages: | $(LANGUAGES)

.PHONY: all all_languages  $(LANGUAGES)

ar:
	python ./BuildLangModel.py ar  

be:
	python ./BuildLangModel.py be  

bg:
	python ./BuildLangModel.py bg  

ca:
	python ./BuildLangModel.py ca  

cs:
	python ./BuildLangModel.py cs  

da:
	python ./BuildLangModel.py da  

de:
	python ./BuildLangModel.py de  

el:
	python ./BuildLangModel.py el  

en:
	python ./BuildLangModel.py en  

eo:
	python ./BuildLangModel.py eo  

es:
	python ./BuildLangModel.py es  

et:
	python ./BuildLangModel.py et  

fi:
	python ./BuildLangModel.py fi  

fr:
	python ./BuildLangModel.py fr  

ga:
	python ./BuildLangModel.py ga  

he:
	python ./BuildLangModel.py he  

hi:
	python ./BuildLangModel.py hi  

hr:
	python ./BuildLangModel.py hr  

hu:
	python ./BuildLangModel.py hu  

it:
	python ./BuildLangModel.py it  

ka:
	python ./BuildLangModel.py ka  

ko:
	python ./BuildLangModel.py ko  

lt:
	python ./BuildLangModel.py lt  

lv:
	python ./BuildLangModel.py lv  

mk:
	python ./BuildLangModel.py mk  

mt:
	python ./BuildLangModel.py mt  

no:
	python ./BuildLangModel.py no  

pl:
	python ./BuildLangModel.py pl  

pt:
	python ./BuildLangModel.py pt  

ro:
	python ./BuildLangModel.py ro  

ru:
	python ./BuildLangModel.py ru  

sk:
	python ./BuildLangModel.py sk  

sl:
	python ./BuildLangModel.py sl  

sr:
	python ./BuildLangModel.py sr  

sv:
	python ./BuildLangModel.py sv  

th:
	python ./BuildLangModel.py th  

tr:
	python ./BuildLangModel.py tr  

uk:
	python ./BuildLangModel.py uk  

vi:
	python ./BuildLangModel.py vi  

