/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsSBCharSetProber-generated.h"
#include "../nsLanguageDetector.h"

#include "../nsLanguageDetector-generated.h"

/********* Language model for: Norwegian *********/

/**
 * Generated by BuildLangModel.py
 * On: 2023-06-20 07:36:10.678658
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */
static const unsigned char Ibm865_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  5, 17, 23,  9,  0, 14, 11, 18,  6, 21, 10,  7, 12,  2,  8, /* 4X */
   15, 29,  1,  4,  3, 16, 13, 24, 27, 20, 26,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  5, 17, 23,  9,  0, 14, 11, 18,  6, 21, 10,  7, 12,  2,  8, /* 6X */
   15, 29,  1,  4,  3, 16, 13, 24, 27, 20, 26,SYM,SYM,SYM,SYM,CTR, /* 7X */
   45, 32, 28, 53, 31, 41, 19, 45, 40, 61, 37, 62, 58, 47, 31, 19, /* 8X */
   28, 25, 25, 36, 30, 46, 63, 48, 64, 30, 32, 22,SYM, 22,SYM,SYM, /* 9X */
   33, 34, 35, 60, 44, 44,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* CX */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* DX */
   39, 43, 65, 51, 56, 56, 42, 49, 66, 67, 68, 69, 70, 71, 72,SYM, /* EX */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_15_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  5, 17, 23,  9,  0, 14, 11, 18,  6, 21, 10,  7, 12,  2,  8, /* 4X */
   15, 29,  1,  4,  3, 16, 13, 24, 27, 20, 26,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  5, 17, 23,  9,  0, 14, 11, 18,  6, 21, 10,  7, 12,  2,  8, /* 6X */
   15, 29,  1,  4,  3, 16, 13, 24, 27, 20, 26,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM, 57,SYM, 57,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM, 59, 42,SYM,SYM, 59,SYM,SYM,SYM, 54, 54, 73,SYM, /* BX */
   41, 33, 53, 38, 31, 19, 25, 45, 37, 28, 40, 74, 47, 34, 58, 75, /* CX */
   52, 44, 46, 35, 36, 76, 30,SYM, 22, 48, 60, 77, 32, 50, 55, 43, /* DX */
   41, 33, 53, 38, 31, 19, 25, 45, 37, 28, 40, 78, 47, 34, 58, 79, /* EX */
   52, 44, 46, 35, 36, 80, 30,SYM, 22, 48, 60, 81, 32, 50, 55, 82, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_1_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  5, 17, 23,  9,  0, 14, 11, 18,  6, 21, 10,  7, 12,  2,  8, /* 4X */
   15, 29,  1,  4,  3, 16, 13, 24, 27, 20, 26,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  5, 17, 23,  9,  0, 14, 11, 18,  6, 21, 10,  7, 12,  2,  8, /* 6X */
   15, 29,  1,  4,  3, 16, 13, 24, 27, 20, 26,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 42,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   41, 33, 53, 38, 31, 19, 25, 45, 37, 28, 40, 83, 47, 34, 58, 84, /* CX */
   52, 44, 46, 35, 36, 85, 30,SYM, 22, 48, 60, 86, 32, 50, 55, 43, /* DX */
   41, 33, 53, 38, 31, 19, 25, 45, 37, 28, 40, 87, 47, 34, 58, 88, /* EX */
   52, 44, 46, 35, 36, 89, 30,SYM, 22, 48, 60, 90, 32, 50, 55, 91, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1252_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  5, 17, 23,  9,  0, 14, 11, 18,  6, 21, 10,  7, 12,  2,  8, /* 4X */
   15, 29,  1,  4,  3, 16, 13, 24, 27, 20, 26,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  5, 17, 23,  9,  0, 14, 11, 18,  6, 21, 10,  7, 12,  2,  8, /* 6X */
   15, 29,  1,  4,  3, 16, 13, 24, 27, 20, 26,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM, 92,SYM,SYM,SYM,SYM,SYM,SYM, 57,SYM, 54,ILL, 59,ILL, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, 57,SYM, 54,ILL, 59, 93, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 42,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   41, 33, 53, 38, 31, 19, 25, 45, 37, 28, 40, 94, 47, 34, 58, 95, /* CX */
   52, 44, 46, 35, 36, 96, 30,SYM, 22, 48, 60, 97, 32, 50, 55, 43, /* DX */
   41, 33, 53, 38, 31, 19, 25, 45, 37, 28, 40, 98, 47, 34, 58, 99, /* EX */
   52, 44, 46, 35, 36,100, 30,SYM, 22, 48, 60,101, 32, 50, 55,102, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const int Unicode_Char_size = 60;
static const unsigned int Unicode_CharOrder[] =
{
  65,  5, 66, 17, 67, 23, 68,  9, 69,  0, 70, 14, 71, 11,72, 18,
  73,  6, 74, 21, 75, 10, 76,  7, 77, 12, 78,  2, 79,  8,80, 15,
  81, 29, 82,  1, 83,  4, 84,  3, 85, 16, 86, 13, 87, 24,88, 27,
  89, 20, 90, 26, 97,  5, 98, 17, 99, 23, 100,  9, 101,  0,102, 14,
  103, 11, 104, 18, 105,  6, 106, 21, 107, 10, 108,  7, 109, 12,110,  2,
  111,  8, 112, 15, 113, 29, 114,  1, 115,  4, 116,  3, 117, 16,118, 13,
  119, 24, 120, 27, 121, 20, 122, 26, 197, 19, 198, 25, 201, 28,216, 22,
  229, 19, 230, 25, 233, 28, 248, 22,
};


/* Model Table:
 * Total considered sequences: 911 / 900
 * - Positive sequences: first 459 (0.9950097008425519)
 * - Probable sequences: next 139 (598-459) (0.003996996306544265)
 * - Neutral sequences: last 302 (0.000993302850903821)
 * - Negative sequences: -11 (off-ratio)
 * Negative sequences: TODO
 */
static const PRUint8 NorwegianLangModel[] =
{
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,2,1,3,3,1,2,3,0,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,2,2,2,1,2,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,1,3,2,1,2,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,0,2,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,2,0,2,2,
  3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,0,3,2,0,3,3,0,3,2,0,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,3,2,3,2,1,3,3,0,2,
  3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,3,2,1,1,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,2,1,3,3,0,2,3,0,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,2,3,3,3,3,2,2,1,1,0,2,0,
  3,3,3,3,3,3,3,3,3,3,3,2,3,3,2,2,3,2,3,2,3,3,2,1,1,1,0,0,1,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,1,1,1,2,1,1,1,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,2,1,2,1,1,1,1,
  3,2,3,3,3,3,3,3,3,3,2,3,3,2,2,2,3,2,3,3,2,3,2,1,0,3,0,0,1,0,
  3,3,2,3,2,3,3,3,3,1,1,2,2,1,3,1,3,2,1,3,3,3,3,3,1,3,0,0,2,0,
  3,3,3,3,3,3,3,3,3,3,2,3,2,2,3,3,3,2,3,3,2,0,3,2,0,1,1,0,0,0,
  3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,2,3,2,0,2,1,1,3,2,0,2,2,1,1,
  3,3,3,1,3,3,3,3,3,2,0,1,2,1,1,2,3,3,1,3,3,2,3,3,1,3,0,0,0,0,
  3,3,3,3,2,3,3,3,3,2,1,1,2,3,2,1,3,1,1,3,3,3,3,2,2,3,1,0,0,1,
  3,3,3,3,3,1,1,3,1,3,3,2,1,3,2,3,0,2,1,0,0,0,0,0,0,0,0,0,0,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,2,3,2,1,1,2,0,2,2,0,0,1,0,0,
  3,2,1,1,1,3,3,1,3,1,1,1,1,0,1,1,3,1,0,2,1,0,3,1,0,2,1,0,1,0,
  3,3,3,3,3,1,1,3,1,3,3,2,3,3,2,3,0,2,1,0,3,0,1,0,0,0,0,0,0,0,
  3,3,2,3,3,3,3,3,3,2,3,1,2,1,1,1,3,2,3,0,2,1,0,3,1,0,1,0,1,1,
  3,2,3,1,2,3,3,3,3,1,1,1,1,0,2,1,1,2,3,0,2,0,0,1,2,0,0,0,0,0,
  0,3,0,1,2,0,1,2,0,1,0,1,0,0,1,2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,
  3,1,1,1,1,3,3,1,3,0,1,0,1,1,1,1,2,1,2,0,2,2,0,0,0,0,2,0,0,0,
  2,0,0,2,1,2,3,2,1,1,1,0,1,2,2,2,1,1,2,0,1,0,0,1,1,0,0,2,0,0,
  2,2,3,1,1,1,0,1,1,1,0,1,2,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,
  0,0,0,0,2,2,1,1,1,0,0,0,0,1,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,
};


const SequenceModel Ibm865NorwegianModel =
{
  Ibm865_CharToOrderMap,
  NorwegianLangModel,
  30,
  (float)0.9990066971490962,
  PR_TRUE,
  "IBM865",
  "no"
};

const SequenceModel Iso_8859_15NorwegianModel =
{
  Iso_8859_15_CharToOrderMap,
  NorwegianLangModel,
  30,
  (float)0.9990066971490962,
  PR_TRUE,
  "ISO-8859-15",
  "no"
};

const SequenceModel Iso_8859_1NorwegianModel =
{
  Iso_8859_1_CharToOrderMap,
  NorwegianLangModel,
  30,
  (float)0.9990066971490962,
  PR_TRUE,
  "ISO-8859-1",
  "no"
};

const SequenceModel Windows_1252NorwegianModel =
{
  Windows_1252_CharToOrderMap,
  NorwegianLangModel,
  30,
  (float)0.9990066971490962,
  PR_TRUE,
  "WINDOWS-1252",
  "no"
};

const LanguageModel NorwegianModel =
{
  "no",
  Unicode_CharOrder,
  60,
  NorwegianLangModel,
  30,
  5,
  (float)0.4596057301531841,
  19,
  (float)0.033375016090770336,
  (float)0.9997315140035675,
};
