/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsSBCharSetProber-generated.h"
#include "../nsLanguageDetector.h"

#include "../nsLanguageDetector-generated.h"

/********* Language model for: Slovak *********/

/**
 * Generated by BuildLangModel.py
 * On: 2023-07-08 23:28:41.407980
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 * IRR: irrelevant character (which does belong to a word)
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */



#define IRR                     (-1)

#define SlovakOrderWidth        44


static const unsigned char Iso_8859_2_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 17, 15, 12,  2, 30, 27, 16,  4, 19, 10,  9, 11,  3,  0, /* 4X */
   13, 40,  5,  6,  7, 14,  8, 33, 35, 21, 18,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 17, 15, 12,  2, 30, 27, 16,  4, 19, 10,  9, 11,  3,  0, /* 6X */
   13, 40,  5,  6,  7, 14,  8, 33, 35, 21, 18,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,249,SYM,249,SYM, 32,249,SYM,SYM, 26,249, 31,249,SYM, 29,249, /* AX */
  SYM,249,SYM,249,SYM, 32,249,SYM,SYM, 26,249, 31,249,SYM, 29,249, /* BX */
   43, 20,249,249, 39, 41,249,249, 24, 25,249,249,249, 23,249, 38, /* CX */
  249,249, 37, 34, 36,249,249,SYM, 42,249, 28,249,249, 22,249,249, /* DX */
   43, 20,249,249, 39, 41,249,249, 24, 25,249,249,249, 23,249, 38, /* EX */
  249,249, 37, 34, 36,249,249,SYM, 42,249, 28,249,249, 22,249,SYM, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1250_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 17, 15, 12,  2, 30, 27, 16,  4, 19, 10,  9, 11,  3,  0, /* 4X */
   13, 40,  5,  6,  7, 14,  8, 33, 35, 21, 18,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 17, 15, 12,  2, 30, 27, 16,  4, 19, 10,  9, 11,  3,  0, /* 6X */
   13, 40,  5,  6,  7, 14,  8, 33, 35, 21, 18,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM,ILL,SYM,SYM,SYM,SYM,ILL,SYM, 26,SYM,249, 31, 29,249, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,ILL,SYM, 26,SYM,249, 31, 29,249, /* 9X */
  SYM,SYM,SYM,249,SYM,249,SYM,SYM,SYM,SYM,249,SYM,SYM,SYM,SYM,249, /* AX */
  SYM,SYM,SYM,249,SYM,SYM,SYM,SYM,SYM,249,249,SYM, 32,SYM, 32,249, /* BX */
   43, 20,249,249, 39, 41,249,249, 24, 25,249,249,249, 23,249, 38, /* CX */
  249,249, 37, 34, 36,249,249,SYM, 42,249, 28,249,249, 22,249,249, /* DX */
   43, 20,249,249, 39, 41,249,249, 24, 25,249,249,249, 23,249, 38, /* EX */
  249,249, 37, 34, 36,249,249,SYM, 42,249, 28,249,249, 22,249,SYM, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Ibm852_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 17, 15, 12,  2, 30, 27, 16,  4, 19, 10,  9, 11,  3,  0, /* 4X */
   13, 40,  5,  6,  7, 14,  8, 33, 35, 21, 18,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 17, 15, 12,  2, 30, 27, 16,  4, 19, 10,  9, 11,  3,  0, /* 6X */
   13, 40,  5,  6,  7, 14,  8, 33, 35, 21, 18,SYM,SYM,SYM,SYM,CTR, /* 7X */
  249,249, 25,249, 39,249,249,249,249,249,249,249,249,249, 39,249, /* 8X */
   25, 41, 41, 36,249, 32, 32,249,249,249,249, 31, 31,249,SYM, 24, /* 9X */
   20, 23, 34, 28,249,249, 29, 29,249,249,SYM,249, 24,249,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 20,249,249,249,SYM,SYM,SYM,SYM,249,249,SYM, /* BX */
  SYM,SYM,SYM,SYM,SYM,SYM,249,249,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* CX */
  249,249, 38,249, 38, 37, 23,249,249,SYM,SYM,SYM,SYM,249,249,SYM, /* DX */
   34,249, 36,249,249, 37, 26, 26, 43, 28, 43,249, 22, 22,249,SYM, /* EX */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,249, 42, 42,SYM,SYM, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Maccentraleurope_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 17, 15, 12,  2, 30, 27, 16,  4, 19, 10,  9, 11,  3,  0, /* 4X */
   13, 40,  5,  6,  7, 14,  8, 33, 35, 21, 18,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 17, 15, 12,  2, 30, 27, 16,  4, 19, 10,  9, 11,  3,  0, /* 6X */
   13, 40,  5,  6,  7, 14,  8, 33, 35, 21, 18,SYM,SYM,SYM,SYM,CTR, /* 7X */
   39,249,249, 25,249,249,249, 20,249, 24, 39, 24,249,249, 25,249, /* 8X */
  249, 38, 23, 38,249,249,249, 34,249, 36,249,249, 28,249,249,249, /* 9X */
  SYM,SYM,249,SYM,SYM,SYM,SYM,249,SYM,SYM,SYM,249,SYM,SYM,249,249, /* AX */
  249,249,SYM,SYM,249,249,SYM,SYM,249,249,249, 32, 32, 41, 41,249, /* BX */
  249,249,SYM,SYM,249, 37,SYM,SYM,SYM,SYM,SYM, 37,249,249,249,249, /* CX */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,249, 43, 43, 42,SYM,SYM, 42,249, /* DX */
  249, 26,SYM,SYM, 26,249,249, 20, 31, 31, 23, 29, 29,249, 34, 36, /* EX */
  249,249, 28,249,249,249,249,249, 22, 22,249,249,249,249,249,SYM, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

#define Unicode_Char_size    88

static const PRUint32 Unicode_CharOrder[] =
{
   65,  1,  66, 17,  67, 15,  68, 12,  69,  2,  70, 30,  71, 27,  72, 16,
   73,  4,  74, 19,  75, 10,  76,  9,  77, 11,  78,  3,  79,  0,  80, 13,
   81, 40,  82,  5,  83,  6,  84,  7,  85, 14,  86,  8,  87, 33,  88, 35,
   89, 21,  90, 18,  97,  1,  98, 17,  99, 15, 100, 12, 101,  2, 102, 30,
  103, 27, 104, 16, 105,  4, 106, 19, 107, 10, 108,  9, 109, 11, 110,  3,
  111,  0, 112, 13, 113, 40, 114,  5, 115,  6, 116,  7, 117, 14, 118,  8,
  119, 33, 120, 35, 121, 21, 122, 18, 193, 20, 196, 39, 201, 25, 205, 23,
  211, 34, 212, 36, 218, 28, 221, 22, 225, 20, 228, 39, 233, 25, 237, 23,
  243, 34, 244, 36, 250, 28, 253, 22, 268, 24, 269, 24, 270, 38, 271, 38,
  313, 41, 314, 41, 317, 32, 318, 32, 327, 37, 328, 37, 340, 43, 341, 43,
  344, 42, 345, 42, 352, 26, 353, 26, 356, 31, 357, 31, 381, 29, 382, 29,
};

static const float OrderToRatio[] =
{
  0.091838529f,  0.089309585f,  0.077843610f,  0.062562879f,  0.061338772f,  0.055581151f,  0.048552595f,  0.047248978f, 
  0.043446905f,  0.042654735f,  0.038806809f,  0.031646794f,  0.030714628f,  0.030154890f,  0.028349582f,  0.026178676f, 
  0.023378277f,  0.017608462f,  0.017604072f,  0.017527001f,  0.017349202f,  0.015306584f,  0.010174065f,  0.009385066f, 
  0.008534361f,  0.008486314f,  0.007260500f,  0.006622959f,  0.006603691f,  0.006321261f,  0.005256417f,  0.003293309f, 
  0.003163314f,  0.001837990f,  0.001721652f,  0.001337274f,  0.001255082f,  0.001105087f,  0.000955091f,  0.000866558f, 
  0.000249748f,  0.000090241f,  0.000087314f,  0.000076583f, 
  0    /* value slot for out-of-bounds index values; range: 0..freq_count(44) */
};


/* Model Table:
 * Number of web pages processed for this model: 976
 * Number of characters consumed for this model: 4100131
 * Total considered sequences: 1735 / 1936
 *
 * - Positive sequences: first 800 (0.9950255427143826)
 * - Probable sequences: next 269 (1069-800) (0.003977380292430666)
 * - Neutral sequences: last 867 (0.0009970769931867407)
 * - Negative sequences: 201 (off-ratio, TODO)
 */
#define SlovakUnicodeCharToOrderIsReduced  0


#define SlovakFCMLowerBound  65
#define SlovakFCMUpperBound  382


static const PRInt16 SlovakUnicodeCharToOrder[] =
{
  1,17,15,12,2,30,27,16,4,19,10,9,11,3,0,13,40,5,6,7,
  14,8,33,35,21,18,IRR,IRR,IRR,IRR,IRR,IRR,1,17,15,12,2,30,27,16,
  4,19,10,9,11,3,0,13,40,5,6,7,14,8,33,35,21,18,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,20,IRR,IRR,39,IRR,IRR,IRR,IRR,25,IRR,IRR,IRR,
  23,IRR,IRR,IRR,IRR,IRR,34,36,IRR,IRR,IRR,IRR,IRR,28,IRR,IRR,22,IRR,IRR,IRR,
  20,IRR,IRR,39,IRR,IRR,IRR,IRR,25,IRR,IRR,IRR,23,IRR,IRR,IRR,IRR,IRR,34,36,
  IRR,IRR,IRR,IRR,IRR,28,IRR,IRR,22,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,24,24,38,38,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,41,41,IRR,IRR,32,32,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,37,37,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,43,43,IRR,IRR,42,
  42,IRR,IRR,IRR,IRR,IRR,IRR,26,26,IRR,IRR,31,31,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,29,29,
};



#define SlovakUnicodeCharToOrderFirstTableChunkSize    58
#define SlovakUnicodeCharToOrderSecondTableChunkOffset 128
#define SlovakUnicodeCharToOrderSecondTableChunkSize   190


static const PRInt16 SlovakUnicodeCharToOrder2[] =
{
  20,IRR,IRR,39,IRR,IRR,IRR,IRR,25,IRR,IRR,IRR,23,IRR,IRR,IRR,IRR,IRR,34,36,
  IRR,IRR,IRR,IRR,IRR,28,IRR,IRR,22,IRR,IRR,IRR,20,IRR,IRR,39,IRR,IRR,IRR,IRR,
  25,IRR,IRR,IRR,23,IRR,IRR,IRR,IRR,IRR,34,36,IRR,IRR,IRR,IRR,IRR,28,IRR,IRR,
  22,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,24,24,38,38,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  41,41,IRR,IRR,32,32,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,37,37,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,43,43,IRR,IRR,42,42,IRR,IRR,IRR,IRR,IRR,IRR,26,
  26,IRR,IRR,31,31,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,29,29,
};

static const PRUint8 SlovakCompactedLangModel[] =
{
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,
  1,1,3,2,3,3,2,3,3,1,3,3,1,3,0,3,3,0,2,0,2,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,
  0,1,3,1,3,3,2,3,3,3,3,3,1,3,1,3,3,0,2,0,1,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  1,2,3,0,3,3,3,3,3,3,3,3,3,3,0,3,3,0,3,1,1,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,
  3,3,3,3,3,3,3,3,3,1,0,2,3,2,2,0,1,0,1,0,0,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,
  0,3,3,3,3,3,1,3,3,3,2,2,3,3,0,2,1,0,2,0,2,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,
  3,3,3,3,3,3,3,3,3,3,1,2,3,2,3,3,1,1,2,0,0,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,
  2,3,2,3,1,3,3,2,3,3,3,3,3,1,2,2,0,1,2,1,0,0,
  3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,1,3,3,
  3,3,2,3,2,2,3,1,2,1,2,3,3,1,1,3,2,1,1,2,2,1,
  3,3,3,3,3,3,3,3,1,3,3,2,3,3,3,3,3,3,3,1,3,3,
  3,3,3,3,3,2,3,2,1,1,2,0,1,1,3,2,3,3,1,1,1,1,
  3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,
  3,3,2,3,3,3,3,2,3,1,0,2,3,1,2,2,0,1,1,0,0,0,
  3,3,3,3,3,3,3,3,3,3,2,3,3,2,3,3,2,2,2,1,3,3,
  3,3,3,3,1,2,3,2,2,1,2,2,3,1,3,3,0,1,1,2,2,1,
  3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,2,3,1,2,3,3,
  3,3,2,3,2,2,3,2,3,0,1,2,3,1,3,1,0,3,1,0,0,2,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,
  3,3,3,3,3,3,3,3,2,0,3,3,3,1,3,3,1,1,1,3,2,1,
  3,3,3,3,3,3,3,3,2,3,3,2,2,3,3,3,3,2,1,2,3,3,
  2,3,2,3,3,2,3,0,2,1,2,1,3,1,3,2,0,3,1,2,2,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,
  0,1,3,1,3,3,1,3,3,3,3,2,1,3,0,1,3,0,1,1,1,0,
  3,3,3,3,3,3,3,3,2,3,3,3,3,2,3,3,3,2,2,1,2,3,
  0,3,1,3,0,2,3,1,1,2,1,1,1,1,1,1,0,0,2,0,0,0,
  3,3,3,3,3,3,3,3,3,3,3,3,2,2,3,3,1,2,2,1,3,3,
  3,2,1,3,3,1,3,1,2,1,3,2,2,1,2,1,0,2,1,2,1,3,
  3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,2,3,2,3,3,3,
  3,3,3,2,2,1,3,2,1,1,2,2,2,1,2,2,0,1,1,1,2,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,
  3,3,1,2,3,2,3,0,1,3,2,1,3,1,1,2,1,1,1,0,0,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,2,3,2,3,1,
  0,3,3,1,3,1,3,1,1,1,1,1,2,0,1,1,1,1,1,0,0,0,
  1,0,0,3,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,
  0,0,3,0,3,3,0,3,1,2,3,1,0,0,0,2,2,0,0,0,1,0,
  3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,0,
  0,1,3,0,3,2,2,3,2,3,1,2,0,2,0,3,0,0,1,0,1,0,
  1,1,0,3,0,3,3,3,3,3,3,3,2,3,2,3,3,3,3,2,0,0,
  0,0,2,0,3,1,0,3,1,1,1,0,0,1,0,2,0,0,0,0,1,0,
  1,2,0,3,0,3,3,3,3,3,3,3,3,3,1,3,3,3,3,3,0,0,
  0,1,3,0,3,1,0,3,1,3,2,1,0,1,0,1,1,0,0,0,1,0,
  3,3,3,3,3,2,3,3,1,3,3,2,1,1,3,1,1,2,1,0,2,1,
  0,3,0,1,3,0,2,0,0,0,1,0,0,0,0,2,0,0,0,0,0,1,
  2,1,2,3,1,3,3,3,2,3,2,3,3,2,1,3,3,2,3,1,0,0,
  0,0,2,1,1,3,0,3,2,1,0,1,0,0,0,0,0,0,0,0,1,0,
  3,3,3,3,3,1,3,3,3,3,3,2,1,3,3,1,1,1,0,0,2,0,
  0,3,2,2,3,0,1,1,1,3,2,0,1,0,0,2,0,0,0,0,0,0,
  3,3,3,3,3,3,3,3,2,3,2,3,2,2,3,2,3,2,1,1,3,3,
  1,2,1,3,1,3,1,1,2,0,1,2,3,1,1,0,1,1,1,0,1,0,
  1,1,0,3,0,3,3,3,3,3,3,3,3,3,0,3,3,3,3,1,0,0,
  0,0,3,0,3,1,0,3,2,3,1,0,0,0,0,1,0,0,0,0,0,0,
  3,3,3,3,3,2,3,1,1,2,3,2,3,1,3,1,1,3,0,1,3,1,
  0,3,0,2,3,0,1,0,0,0,1,0,0,0,1,3,2,0,0,0,0,0,
  3,3,3,2,3,3,2,3,1,3,2,2,1,2,3,2,1,2,2,1,3,3,
  1,2,0,3,0,2,2,0,3,0,1,0,3,1,0,0,0,1,0,0,0,0,
  3,3,1,1,1,2,1,1,1,1,2,2,2,1,2,0,1,1,0,1,1,0,
  0,0,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,
  3,3,1,3,0,1,3,1,3,0,3,3,1,1,3,0,1,3,0,1,1,0,
  1,0,2,1,2,1,3,0,0,0,0,0,0,0,1,2,0,0,0,0,0,0,
  3,3,3,3,3,3,3,1,1,2,2,2,2,1,2,2,3,2,1,1,1,2,
  0,0,0,1,1,1,0,0,1,0,0,3,1,1,0,0,0,1,0,0,0,0,
  1,1,0,3,0,3,2,3,1,3,1,3,3,3,1,2,1,3,3,2,0,0,
  0,0,1,1,1,3,0,1,2,0,0,1,1,1,0,1,0,0,0,0,0,0,
  3,3,3,2,3,1,2,3,2,1,2,1,1,3,3,2,1,1,0,0,1,2,
  0,1,0,1,0,1,1,0,2,0,0,1,3,2,0,0,0,0,1,0,0,0,
  0,0,0,1,0,3,3,2,3,3,2,1,3,1,0,2,1,3,3,2,0,0,
  0,0,1,0,1,1,0,3,1,0,1,0,0,0,0,2,0,0,0,0,0,0,
  3,3,1,0,0,0,1,1,0,0,1,2,0,0,3,0,1,0,0,0,1,0,
  0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,
  3,3,1,1,0,0,1,1,0,0,0,2,0,0,2,0,0,0,0,1,1,0,
  0,0,0,0,0,0,0,3,0,0,1,0,0,0,0,0,0,0,0,0,0,0,
  1,0,0,2,1,1,2,3,0,1,1,1,1,0,1,1,1,1,3,0,0,0,
  0,0,3,0,0,1,0,0,1,3,0,0,0,0,0,0,0,1,0,0,0,0,
  1,2,1,0,1,0,1,0,2,1,0,1,1,1,3,1,1,1,0,1,0,0,
  0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,
  0,0,1,1,0,0,0,0,1,0,1,0,0,2,0,0,1,2,1,0,0,0,
  0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,2,0,0,0,0,0,0,
  1,1,2,1,2,0,1,0,0,0,1,1,0,0,0,0,0,1,0,0,2,0,
  0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,1,0,0,0,2,1,1,0,1,1,1,0,1,0,1,0,0,0,0,
  0,1,1,0,1,0,0,1,0,0,0,0,0,0,0,3,0,0,0,0,0,0,
};


const SequenceModel Iso_8859_2SlovakModel =
{
  Iso_8859_2_CharToOrderMap,
  SlovakCompactedLangModel,
  SlovakOrderWidth,
  0.9990029230068133f,
  PR_TRUE,
  "ISO-8859-2",
  "sk"
};

const SequenceModel Windows_1250SlovakModel =
{
  Windows_1250_CharToOrderMap,
  SlovakCompactedLangModel,
  SlovakOrderWidth,
  0.9990029230068133f,
  PR_TRUE,
  "WINDOWS-1250",
  "sk"
};

const SequenceModel Ibm852SlovakModel =
{
  Ibm852_CharToOrderMap,
  SlovakCompactedLangModel,
  SlovakOrderWidth,
  0.9990029230068133f,
  PR_TRUE,
  "IBM852",
  "sk"
};

const SequenceModel MaccentraleuropeSlovakModel =
{
  Maccentraleurope_CharToOrderMap,
  SlovakCompactedLangModel,
  SlovakOrderWidth,
  0.9990029230068133f,
  PR_TRUE,
  "MacCentralEurope",
  "sk"
};

const LanguageModel SlovakModel =
{
  "sk",
  Unicode_CharOrder,
  Unicode_Char_size,

  SlovakFCMLowerBound,
  SlovakFCMUpperBound,
  SlovakUnicodeCharToOrderIsReduced,
  SlovakUnicodeCharToOrder,
  SlovakUnicodeCharToOrderFirstTableChunkSize,
  SlovakUnicodeCharToOrderSecondTableChunkOffset,
  SlovakUnicodeCharToOrderSecondTableChunkSize,
  SlovakUnicodeCharToOrder2,
  OrderToRatio,
  SlovakCompactedLangModel,
  SlovakOrderWidth,
  6,
  0.43847452678950993f,
  27,
  0.034220613926725756f,
  0.9996865953795138f,
};
