/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsSBCharSetProber-generated.h"
#include "../nsLanguageDetector.h"

#include "../nsLanguageDetector-generated.h"

/********* Language model for: Portuguese *********/

/**
 * Generated by BuildLangModel.py
 * On: 2023-06-20 07:57:00.842779
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */
static const unsigned char Iso_8859_15_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  0, 17, 11,  7,  1, 16, 14, 18,  4, 27, 30, 12,  9,  6,  2, /* 4X */
   13, 20,  5,  3,  8, 10, 15, 33, 26, 29, 25,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  0, 17, 11,  7,  1, 16, 14, 18,  4, 27, 30, 12,  9,  6,  2, /* 6X */
   13, 20,  5,  3,  8, 10, 15, 33, 26, 29, 25,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM, 47,SYM, 47,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM, 54, 56,SYM,SYM, 54,SYM,SYM,SYM, 61, 62, 63,SYM, /* BX */
   36, 24, 35, 19, 49, 45, 50, 21, 42, 22, 31, 43, 57, 23, 44, 40, /* CX */
   59, 41, 58, 28, 37, 32, 39,SYM, 48, 64, 34, 46, 38, 51, 65, 52, /* DX */
   36, 24, 35, 19, 49, 45, 50, 21, 42, 22, 31, 43, 57, 23, 44, 40, /* EX */
   59, 41, 58, 28, 37, 32, 39,SYM, 48, 66, 34, 46, 38, 51, 67, 68, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_1_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  0, 17, 11,  7,  1, 16, 14, 18,  4, 27, 30, 12,  9,  6,  2, /* 4X */
   13, 20,  5,  3,  8, 10, 15, 33, 26, 29, 25,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  0, 17, 11,  7,  1, 16, 14, 18,  4, 27, 30, 12,  9,  6,  2, /* 6X */
   13, 20,  5,  3,  8, 10, 15, 33, 26, 29, 25,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 56,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   36, 24, 35, 19, 49, 45, 50, 21, 42, 22, 31, 43, 57, 23, 44, 40, /* CX */
   59, 41, 58, 28, 37, 32, 39,SYM, 48, 69, 34, 46, 38, 51, 70, 52, /* DX */
   36, 24, 35, 19, 49, 45, 50, 21, 42, 22, 31, 43, 57, 23, 44, 40, /* EX */
   59, 41, 58, 28, 37, 32, 39,SYM, 48, 71, 34, 46, 38, 51, 72, 73, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1252_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  0, 17, 11,  7,  1, 16, 14, 18,  4, 27, 30, 12,  9,  6,  2, /* 4X */
   13, 20,  5,  3,  8, 10, 15, 33, 26, 29, 25,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  0, 17, 11,  7,  1, 16, 14, 18,  4, 27, 30, 12,  9,  6,  2, /* 6X */
   13, 20,  5,  3,  8, 10, 15, 33, 26, 29, 25,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM, 74,SYM,SYM,SYM,SYM,SYM,SYM, 47,SYM, 75,ILL, 54,ILL, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, 47,SYM, 76,ILL, 54, 77, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 56,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   36, 24, 35, 19, 49, 45, 50, 21, 42, 22, 31, 43, 57, 23, 44, 40, /* CX */
   59, 41, 58, 28, 37, 32, 39,SYM, 48, 78, 34, 46, 38, 51, 79, 52, /* DX */
   36, 24, 35, 19, 49, 45, 50, 21, 42, 22, 31, 43, 57, 23, 44, 40, /* EX */
   59, 41, 58, 28, 37, 32, 39,SYM, 48, 80, 34, 46, 38, 51, 81, 82, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_9_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  0, 17, 11,  7,  1, 16, 14, 18,  4, 27, 30, 12,  9,  6,  2, /* 4X */
   13, 20,  5,  3,  8, 10, 15, 33, 26, 29, 25,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  0, 17, 11,  7,  1, 16, 14, 18,  4, 27, 30, 12,  9,  6,  2, /* 6X */
   13, 20,  5,  3,  8, 10, 15, 33, 26, 29, 25,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 56,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   36, 24, 35, 19, 49, 45, 50, 21, 42, 22, 31, 43, 57, 23, 44, 40, /* CX */
   60, 41, 58, 28, 37, 32, 39,SYM, 48, 83, 34, 46, 38, 84, 55, 52, /* DX */
   36, 24, 35, 19, 49, 45, 50, 21, 42, 22, 31, 43, 57, 23, 44, 40, /* EX */
   60, 41, 58, 28, 37, 32, 39,SYM, 48, 85, 34, 46, 38, 53, 55, 86, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const int Unicode_Char_size = 76;
static const unsigned int Unicode_CharOrder[] =
{
  65,  0, 66, 17, 67, 11, 68,  7, 69,  1, 70, 16, 71, 14,72, 18,
  73,  4, 74, 27, 75, 30, 76, 12, 77,  9, 78,  6, 79,  2,80, 13,
  81, 20, 82,  5, 83,  3, 84,  8, 85, 10, 86, 15, 87, 33,88, 26,
  89, 29, 90, 25, 97,  0, 98, 17, 99, 11, 100,  7, 101,  1,102, 16,
  103, 14, 104, 18, 105,  4, 106, 27, 107, 30, 108, 12, 109,  9,110,  6,
  111,  2, 112, 13, 113, 20, 114,  5, 115,  3, 116,  8, 117, 10,118, 15,
  119, 33, 120, 26, 121, 29, 122, 25, 192, 36, 193, 24, 194, 35,195, 19,
  199, 21, 201, 22, 202, 31, 205, 23, 211, 28, 212, 37, 213, 32,218, 34,
  224, 36, 225, 24, 226, 35, 227, 19, 231, 21, 233, 22, 234, 31,237, 23,
  243, 28, 244, 37, 245, 32, 250, 34,
};


/* Model Table:
 * Total considered sequences: 1144 / 1444
 * - Positive sequences: first 544 (0.9950085114737821)
 * - Probable sequences: next 179 (723-544) (0.003997341746983629)
 * - Neutral sequences: last 721 (0.0009941467792342618)
 * - Negative sequences: 300 (off-ratio)
 * Negative sequences: TODO
 */
static const PRUint8 PortugueseLangModel[] =
{
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,2,3,0,3,3,3,1,3,3,0,0,3,3,0,0,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,1,3,1,3,3,3,2,3,3,0,2,3,2,2,0,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,1,1,3,3,3,3,1,3,3,1,0,3,0,0,0,0,
  3,3,3,3,3,2,3,3,3,3,3,3,3,3,2,2,3,3,3,3,3,1,3,3,3,1,1,1,3,3,3,2,3,3,1,1,0,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,2,1,3,3,3,3,3,2,3,3,3,2,2,2,0,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,2,1,2,3,3,3,3,2,2,2,3,1,3,
  3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,1,2,3,2,0,3,
  3,3,3,3,3,3,3,3,2,3,3,3,2,1,3,3,2,2,2,3,2,0,3,3,3,2,1,2,3,3,1,3,1,2,3,2,0,2,
  3,3,3,3,3,3,3,2,3,3,3,3,3,2,2,3,2,3,3,3,1,0,3,3,3,2,1,1,3,3,1,3,2,3,3,3,0,3,
  3,3,3,3,3,2,2,2,2,3,3,3,2,3,2,1,1,3,1,3,0,0,3,3,3,1,1,1,3,3,1,3,2,2,3,2,0,3,
  3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,2,1,2,3,2,3,3,3,3,3,1,2,3,3,0,1,0,2,0,0,
  3,3,3,3,3,3,3,2,3,2,3,3,3,1,1,1,1,2,3,2,2,3,3,3,3,1,1,1,3,2,3,3,1,2,2,3,1,2,
  3,3,3,3,3,2,2,3,3,3,3,3,3,3,3,3,3,3,3,2,3,2,3,3,3,1,1,1,3,3,3,3,2,2,2,3,0,3,
  3,3,3,3,3,3,2,2,3,2,3,2,3,3,1,1,1,1,3,2,0,3,3,3,3,1,1,1,3,2,1,1,2,1,3,1,0,2,
  3,3,3,3,3,3,3,1,2,3,3,1,3,1,3,1,1,2,3,2,1,0,3,2,3,0,1,1,2,2,1,3,1,1,1,3,0,1,
  3,3,3,2,3,3,1,2,1,1,3,1,1,1,0,0,0,1,2,2,0,0,3,3,3,0,0,1,2,2,1,2,1,1,0,1,1,1,
  3,3,3,2,3,3,1,1,3,2,3,2,3,1,1,1,3,2,1,2,0,0,3,3,2,0,1,1,3,1,1,2,1,1,2,2,0,1,
  3,3,3,3,3,3,2,2,3,2,3,3,3,1,2,2,1,3,2,1,0,0,3,2,3,1,0,3,2,3,1,2,1,1,1,1,0,3,
  3,3,3,2,3,3,3,1,3,3,3,1,2,1,1,1,1,2,1,3,1,0,2,2,3,1,1,0,2,3,1,1,3,2,1,1,0,1,
  0,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,
  2,0,1,1,1,1,1,1,1,1,3,1,1,0,1,1,1,1,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,0,
  3,0,3,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,3,0,0,0,0,1,0,0,0,1,0,0,0,3,0,1,0,0,1,
  1,1,1,3,2,3,3,3,3,3,2,3,3,3,2,1,1,1,1,0,1,0,0,0,0,1,2,1,0,0,0,0,0,0,0,0,0,0,
  3,1,3,3,0,3,3,3,3,3,0,3,3,3,3,3,3,3,0,0,3,2,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,
  0,1,0,3,1,3,2,3,3,1,2,3,3,3,3,3,3,2,1,0,2,0,0,0,0,1,2,0,0,0,0,0,0,0,0,0,0,0,
  3,3,3,1,3,1,1,1,1,2,3,1,1,1,1,0,1,1,1,2,1,0,2,1,1,3,1,0,1,2,1,1,2,1,1,2,0,2,
  3,3,3,1,3,1,0,0,3,1,3,3,1,3,0,2,2,1,1,2,0,0,2,2,1,1,3,1,1,2,0,1,1,1,1,0,0,1,
  3,3,3,1,3,1,1,1,1,1,3,0,1,1,0,0,1,1,2,2,1,0,1,0,3,1,1,1,1,1,2,0,1,1,2,1,1,1,
  0,0,0,3,3,3,3,3,3,2,0,3,3,3,3,3,3,2,0,0,1,0,0,0,0,1,3,0,0,0,1,0,0,1,0,0,0,0,
  3,3,3,3,2,2,3,2,3,3,2,2,3,2,1,1,1,2,1,1,1,0,0,0,1,1,2,1,0,1,1,0,0,2,0,0,0,0,
  3,3,3,3,3,3,2,2,2,3,3,1,3,1,2,1,1,2,2,0,1,0,1,0,1,0,1,1,1,3,2,1,0,2,0,0,0,0,
  0,1,0,3,1,0,3,0,1,3,2,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,
  0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  3,3,3,3,3,3,3,1,1,1,1,1,2,1,1,0,2,2,3,0,0,0,0,1,0,1,0,1,1,2,1,0,0,3,0,0,0,0,
  0,0,1,3,0,2,3,3,2,3,0,3,3,1,1,2,0,3,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,3,0,1,3,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,3,1,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  1,0,0,3,0,1,3,1,1,3,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};


const SequenceModel Iso_8859_15PortugueseModel =
{
  Iso_8859_15_CharToOrderMap,
  PortugueseLangModel,
  38,
  (float)0.9990058532207657,
  PR_TRUE,
  "ISO-8859-15",
  "pt"
};

const SequenceModel Iso_8859_1PortugueseModel =
{
  Iso_8859_1_CharToOrderMap,
  PortugueseLangModel,
  38,
  (float)0.9990058532207657,
  PR_TRUE,
  "ISO-8859-1",
  "pt"
};

const SequenceModel Windows_1252PortugueseModel =
{
  Windows_1252_CharToOrderMap,
  PortugueseLangModel,
  38,
  (float)0.9990058532207657,
  PR_TRUE,
  "WINDOWS-1252",
  "pt"
};

const SequenceModel Iso_8859_9PortugueseModel =
{
  Iso_8859_9_CharToOrderMap,
  PortugueseLangModel,
  38,
  (float)0.9990058532207657,
  PR_TRUE,
  "ISO-8859-9",
  "pt"
};

const LanguageModel PortugueseModel =
{
  "pt",
  Unicode_CharOrder,
  76,
  PortugueseLangModel,
  38,
  4,
  (float)0.4130926402566398,
  22,
  (float)0.030559241377840305,
  (float)0.9999030806369099,
};
