/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsSBCharSetProber-generated.h"
#include "../nsLanguageDetector.h"

#include "../nsLanguageDetector-generated.h"

/********* Language model for: Czech *********/

/**
 * Generated by BuildLangModel.py
 * On: 2023-07-06 22:51:44.389940
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */
static const unsigned char Iso_8859_2_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 21, 15, 11,  0, 31, 29, 17,  5, 22, 10,  7, 12,  3,  1, /* 4X */
   14, 39,  8,  6,  4, 13,  9, 33, 34, 19, 18,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 21, 15, 11,  0, 31, 29, 17,  5, 22, 10,  7, 12,  3,  1, /* 6X */
   14, 39,  8,  6,  4, 13,  9, 33, 34, 19, 18,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM, 59,SYM, 50,SYM, 49, 54,SYM,SYM, 30, 58, 38, 67,SYM, 27, 63, /* AX */
  SYM, 59,SYM, 50,SYM, 49, 54,SYM,SYM, 30, 58, 38, 67,SYM, 27, 63, /* BX */
   69, 20, 51, 48, 45, 73, 44, 46, 28, 24, 62, 43, 23, 16, 52, 40, /* CX */
   57, 53, 36, 37, 47, 60, 42,SYM, 25, 32, 35, 70, 41, 26, 71, 55, /* DX */
   69, 20, 51, 48, 45, 74, 44, 46, 28, 24, 62, 43, 23, 16, 52, 40, /* EX */
   57, 53, 36, 37, 47, 60, 42,SYM, 25, 32, 35, 70, 41, 26, 71,SYM, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1250_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 21, 15, 11,  0, 31, 29, 17,  5, 22, 10,  7, 12,  3,  1, /* 4X */
   14, 39,  8,  6,  4, 13,  9, 33, 34, 19, 18,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 21, 15, 11,  0, 31, 29, 17,  5, 22, 10,  7, 12,  3,  1, /* 6X */
   14, 39,  8,  6,  4, 13,  9, 33, 34, 19, 18,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM,ILL,SYM,SYM,SYM,SYM,ILL,SYM, 30,SYM, 54, 38, 27, 67, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,ILL,SYM, 30,SYM, 54, 38, 27, 67, /* 9X */
  SYM,SYM,SYM, 50,SYM, 59,SYM,SYM,SYM,SYM, 58,SYM,SYM,SYM,SYM, 63, /* AX */
  SYM,SYM,SYM, 50,SYM,SYM,SYM,SYM,SYM, 59, 58,SYM, 49,SYM, 49, 63, /* BX */
   69, 20, 51, 48, 45, 75, 44, 46, 28, 24, 62, 43, 23, 16, 52, 40, /* CX */
   57, 53, 36, 37, 47, 60, 42,SYM, 25, 32, 35, 70, 41, 26, 71, 55, /* DX */
   69, 20, 51, 48, 45, 76, 44, 46, 28, 24, 62, 43, 23, 16, 52, 40, /* EX */
   57, 53, 36, 37, 47, 60, 42,SYM, 25, 32, 35, 70, 41, 26, 71,SYM, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Ibm852_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 21, 15, 11,  0, 31, 29, 17,  5, 22, 10,  7, 12,  3,  1, /* 4X */
   14, 39,  8,  6,  4, 13,  9, 33, 34, 19, 18,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 21, 15, 11,  0, 31, 29, 17,  5, 22, 10,  7, 12,  3,  1, /* 6X */
   14, 39,  8,  6,  4, 13,  9, 33, 34, 19, 18,SYM,SYM,SYM,SYM,CTR, /* 7X */
   46, 41, 24, 51, 45, 32, 44, 46, 50, 43, 60, 60, 52, 67, 45, 44, /* 8X */
   24, 77, 78, 47, 42, 49, 49, 54, 54, 42, 41, 38, 38, 50,SYM, 28, /* 9X */
   20, 16, 37, 35, 59, 59, 27, 27, 62, 62,SYM, 67, 28, 58,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 20, 51, 23, 58,SYM,SYM,SYM,SYM, 63, 63,SYM, /* BX */
  SYM,SYM,SYM,SYM,SYM,SYM, 48, 48,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* CX */
   57, 57, 40, 43, 40, 36, 16, 52, 23,SYM,SYM,SYM,SYM, 71, 32,SYM, /* DX */
   37, 55, 47, 53, 53, 36, 30, 30, 69, 35, 69, 70, 26, 26, 71,SYM, /* EX */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, 70, 25, 25,SYM,SYM, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Maccentraleurope_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 21, 15, 11,  0, 31, 29, 17,  5, 22, 10,  7, 12,  3,  1, /* 4X */
   14, 39,  8,  6,  4, 13,  9, 33, 34, 19, 18,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 21, 15, 11,  0, 31, 29, 17,  5, 22, 10,  7, 12,  3,  1, /* 6X */
   14, 39,  8,  6,  4, 13,  9, 33, 34, 19, 18,SYM,SYM,SYM,SYM,CTR, /* 7X */
   45, 56, 56, 24, 59, 42, 41, 20, 59, 28, 45, 28, 44, 44, 24, 67, /* 8X */
   67, 40, 16, 40, 64, 64, 61, 37, 61, 47, 42, 66, 35, 23, 23, 41, /* 9X */
  SYM,SYM, 62,SYM,SYM,SYM,SYM, 55,SYM,SYM,SYM, 62,SYM,SYM, 79, 80, /* AX */
   81, 82,SYM,SYM, 83, 84,SYM,SYM, 50, 85, 86, 49, 49, 87, 88, 72, /* BX */
   72, 53,SYM,SYM, 53, 36,SYM,SYM,SYM,SYM,SYM, 36, 60, 66, 60, 68, /* CX */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, 68, 69, 69, 25,SYM,SYM, 25, 89, /* DX */
   90, 30,SYM,SYM, 30, 54, 54, 20, 38, 38, 16, 27, 27, 65, 37, 47, /* EX */
   65, 32, 35, 32, 70, 70, 91, 92, 26, 26, 93, 63, 50, 63, 94,SYM, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

#define Unicode_Char_size    82

static const unsigned int Unicode_CharOrder[] =
{
  65,  2, 66, 21, 67, 15, 68, 11, 69,  0, 70, 31, 71, 29, 72, 17,
  73,  5, 74, 22, 75, 10, 76,  7, 77, 12, 78,  3, 79,  1, 80, 14,
  81, 39, 82,  8, 83,  6, 84,  4, 85, 13, 86,  9, 87, 33, 88, 34,
  89, 19, 90, 18, 97,  2, 98, 21, 99, 15, 100, 11, 101,  0, 102, 31,
  103, 29, 104, 17, 105,  5, 106, 22, 107, 10, 108,  7, 109, 12, 110,  3,
  111,  1, 112, 14, 113, 39, 114,  8, 115,  6, 116,  4, 117, 13, 118,  9,
  119, 33, 120, 34, 121, 19, 122, 18, 193, 20, 201, 24, 205, 16, 211, 37,
  218, 35, 221, 26, 225, 20, 233, 24, 237, 16, 243, 37, 250, 35, 253, 26,
  268, 28, 269, 28, 270, 40, 271, 40, 282, 23, 283, 23, 327, 36, 328, 36,
  344, 25, 345, 25, 352, 30, 353, 30, 356, 38, 357, 38, 366, 32, 367, 32,
  381, 27, 382, 27,
};

static const float OrderToRatio[] =
{
  0.080836610,  0.080836610,  0.078774119,  0.078774119,  0.075954598,  0.075954598,  0.066251820,  0.066251820, 
  0.052331503,  0.052331503,  0.050912534,  0.050912534,  0.048275363,  0.048275363,  0.047304671,  0.047304671, 
  0.046451632,  0.046451632,  0.040229163,  0.040229163,  0.035227196,  0.035227196,  0.034286205,  0.034286205, 
  0.030695841,  0.030695841,  0.030563913,  0.030563913,  0.030257233,  0.030257233,  0.027170635,  0.027170635, 
  0.025488500,  0.025488500,  0.023862545,  0.023862545,  0.018851369,  0.018851369,  0.018847685,  0.018847685, 
  0.018253205,  0.018253205,  0.017645141,  0.017645141,  0.016383656,  0.016383656,  0.012106946,  0.012106946, 
  0.010509079,  0.010509079,  0.009324724,  0.009324724,  0.007943514,  0.007943514,  0.007662621,  0.007662621, 
  0.007638906,  0.007638906,  0.007110966,  0.007110966,  0.005814253,  0.005814253,  0.005648250,  0.005648250, 
  0.004318153,  0.004318153,  0.002551751,  0.002551751,  0.001458571,  0.001458571,  0.001267472,  0.001267472, 
  0.000525868,  0.000525868,  0.000329243,  0.000329243,  0.000258560,  0.000258560,  0.000223563,  0.000223563, 
  0.000151958,  0.000151958, 
};


/* Model Table:
 * Number of web pages processed for this model: 703
 * Number of characters consumed for this model: 4343292
 * Total considered sequences: 1640 / 1681
 *
 * - Positive sequences: first 779 (0.995009604797878)
 * - Probable sequences: next 235 (1014-779) (0.0039913052781319625)
 * - Neutral sequences: last 667 (0.0009990899239900042)
 * - Negative sequences: 41 (off-ratio, TODO)
 */


#define CzechUnicodeAlphabetWidth         41
#define CzechUnicodeCharToOrderIsReduced  0


#define CzechFCMLowerBound  97
#define CzechFCMUpperBound  382


static const PRUint8 CzechUnicodeCharToOrder[] =
{
  3,22,16,12,1,32,30,18,6,23,11,8,13,4,2,15,40,9,7,5,
  14,10,34,35,20,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,21,0,0,0,0,0,0,0,25,0,0,0,
  17,0,0,0,0,0,38,0,0,0,0,0,0,36,0,0,27,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,29,0,41,0,0,0,0,0,
  0,0,0,0,0,0,24,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,37,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,26,0,0,0,0,0,0,0,31,0,0,0,
  39,0,0,0,0,0,0,0,0,0,33,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,28,
};

static const PRUint8 CzechCompactedLangModel[] =
{
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,
  3,3,0,1,3,1,3,3,3,3,3,1,3,3,2,3,1,1,2,2,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,3,3,2,
  3,3,0,1,3,0,3,3,3,3,3,0,3,3,1,2,0,3,1,3,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,3,3,1,
  3,3,0,1,3,1,3,3,3,3,3,0,3,3,2,3,1,3,2,2,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,
  3,3,3,3,0,3,3,3,3,3,3,3,2,2,1,1,2,0,2,1,
  0,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,
  3,2,3,3,3,3,1,2,2,3,3,3,3,1,2,2,2,0,1,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,
  3,3,0,3,3,0,3,3,3,3,3,1,2,3,1,2,3,1,2,1,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,
  3,2,1,3,1,2,1,2,2,1,3,3,3,1,1,2,3,2,3,0,
  0,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,
  3,2,0,3,0,3,2,3,3,3,3,3,2,1,1,2,2,0,1,1,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  3,2,0,3,0,3,3,3,3,3,3,3,2,2,2,2,2,2,2,1,
  0,3,3,3,3,2,3,3,3,3,1,3,3,1,3,2,3,3,3,3,3,3,
  3,1,3,3,3,3,3,3,2,3,2,3,1,1,1,2,1,0,0,0,
  0,3,3,3,3,3,3,3,3,3,3,2,3,3,3,1,3,1,2,2,3,3,
  2,1,0,3,3,3,3,3,2,1,2,3,2,0,1,1,3,0,0,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,2,1,0,1,0,
  0,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,2,2,3,3,
  3,2,3,3,3,3,3,2,2,2,2,3,2,1,1,1,2,0,1,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,1,3,3,2,3,
  3,3,0,1,3,0,3,3,3,3,3,1,2,3,1,3,1,2,1,2,
  0,3,3,3,3,3,3,3,3,3,1,3,2,2,3,3,3,3,3,1,3,3,
  2,2,3,3,3,2,0,2,1,3,2,3,1,1,1,2,2,1,1,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,2,
  2,1,0,3,0,0,1,1,2,0,1,3,1,1,1,1,1,0,2,0,
  0,1,1,2,3,3,1,3,3,3,3,3,3,3,1,3,3,1,3,3,1,0,
  3,3,0,1,3,0,3,3,1,3,1,0,0,0,0,2,0,2,1,1,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,1,1,1,3,3,
  2,1,0,3,3,3,3,2,1,1,1,3,2,1,1,1,1,1,1,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
  3,3,0,2,3,3,1,2,1,3,2,3,2,2,2,2,3,0,1,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,3,1,1,
  3,3,0,0,3,0,3,3,2,3,2,2,2,2,2,2,0,1,1,0,
  0,1,0,0,3,3,1,3,3,3,3,3,3,3,1,3,3,1,3,3,0,0,
  3,3,0,0,3,0,3,3,2,3,1,0,0,0,0,1,1,1,1,2,
  0,3,3,3,3,3,3,3,3,3,3,3,3,2,3,1,3,3,2,2,3,3,
  3,3,3,2,3,3,2,3,1,2,1,2,1,0,1,1,2,0,0,0,
  0,3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,2,3,1,3,
  2,1,0,0,0,0,2,3,1,3,1,3,1,1,2,2,2,0,1,1,
  0,0,1,0,3,3,0,3,3,3,3,3,3,3,1,3,3,0,3,3,0,0,
  1,3,0,0,3,0,3,3,0,3,0,0,0,0,0,2,0,2,0,2,
  0,2,1,1,3,3,1,3,3,3,3,3,3,3,1,2,2,0,3,3,0,0,
  2,1,0,0,3,0,3,3,1,1,2,0,1,1,0,0,0,0,0,0,
  0,3,3,3,3,1,3,3,1,1,1,3,1,2,2,1,1,3,2,0,0,3,
  2,0,0,0,0,0,0,2,0,1,0,3,0,0,1,1,0,0,0,0,
  0,0,0,0,3,3,0,3,2,3,3,3,3,3,2,2,3,0,3,3,0,0,
  3,3,0,0,2,0,2,2,0,3,1,0,0,0,0,0,0,0,0,0,
  0,3,3,3,3,2,3,3,2,2,1,3,3,2,3,1,2,3,1,0,0,3,
  3,0,0,1,0,0,0,0,0,3,0,3,0,0,0,3,0,0,0,2,
  0,3,3,3,3,3,3,2,3,2,1,3,1,1,3,1,2,3,1,0,0,3,
  2,1,0,0,0,0,0,1,0,0,1,3,0,0,1,1,0,1,0,0,
  0,3,3,3,3,3,3,3,3,3,2,2,2,3,3,2,1,1,3,1,3,3,
  3,1,0,2,1,0,0,1,3,1,2,2,2,0,0,0,2,0,1,0,
  0,3,3,3,3,3,3,3,3,2,3,3,0,2,3,3,2,3,0,0,0,2,
  1,1,0,2,0,0,0,1,0,3,0,1,0,0,1,1,1,3,0,0,
  0,3,3,3,2,3,3,2,3,3,1,2,2,2,3,2,2,1,1,1,3,3,
  1,1,0,3,0,0,0,0,2,0,3,1,1,1,2,0,1,0,1,0,
  0,1,1,0,2,2,0,3,3,3,3,3,3,3,0,1,2,0,1,3,0,0,
  3,3,0,0,2,0,3,2,0,1,0,0,0,0,0,1,0,0,0,0,
  0,3,3,3,3,2,3,3,3,3,0,2,1,2,2,1,1,0,3,1,3,1,
  2,1,1,0,0,0,0,1,2,0,1,0,3,0,0,0,1,0,0,0,
  0,3,3,3,2,3,3,2,2,1,2,2,1,2,3,3,2,1,1,0,2,1,
  2,0,0,1,0,0,0,0,1,0,2,1,1,2,0,0,0,0,0,0,
  0,0,1,1,3,3,1,3,2,3,2,2,3,3,0,3,1,0,2,3,0,0,
  2,1,0,0,3,0,2,3,1,1,1,0,0,0,0,0,0,1,0,0,
  0,0,3,2,0,1,0,2,0,0,0,3,1,1,3,0,1,0,1,0,0,2,
  0,0,0,0,0,0,0,0,0,1,0,2,0,0,0,0,0,0,0,0,
  0,1,1,1,3,2,0,1,3,2,1,1,3,1,0,2,1,0,1,3,0,0,
  1,1,0,0,0,0,1,1,1,1,1,0,1,0,0,0,0,0,0,0,
  0,0,2,3,0,0,2,1,0,0,0,1,0,1,2,0,0,0,0,0,0,2,
  0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,
  0,1,1,1,0,0,1,1,1,1,1,0,1,1,3,1,0,1,0,0,1,0,
  1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,
  0,0,2,3,0,1,0,1,0,0,0,1,0,1,1,0,0,0,0,0,0,2,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
};


const SequenceModel Iso_8859_2CzechModel =
{
  Iso_8859_2_CharToOrderMap,
  CzechFCMLowerBound,
  CzechFCMUpperBound,
  CzechUnicodeCharToOrder,
  CzechCompactedLangModel,
  41,
  0.99900091007601f,
  PR_TRUE,
  "ISO-8859-2",
  "cs"
};

const SequenceModel Windows_1250CzechModel =
{
  Windows_1250_CharToOrderMap,
  CzechFCMLowerBound,
  CzechFCMUpperBound,
  CzechUnicodeCharToOrder,
  CzechCompactedLangModel,
  41,
  0.99900091007601f,
  PR_TRUE,
  "WINDOWS-1250",
  "cs"
};

const SequenceModel Ibm852CzechModel =
{
  Ibm852_CharToOrderMap,
  CzechFCMLowerBound,
  CzechFCMUpperBound,
  CzechUnicodeCharToOrder,
  CzechCompactedLangModel,
  41,
  0.99900091007601f,
  PR_TRUE,
  "IBM852",
  "cs"
};

const SequenceModel MaccentraleuropeCzechModel =
{
  Maccentraleurope_CharToOrderMap,
  CzechFCMLowerBound,
  CzechFCMUpperBound,
  CzechUnicodeCharToOrder,
  CzechCompactedLangModel,
  41,
  0.99900091007601f,
  PR_TRUE,
  "MacCentralEurope",
  "cs"
};

const LanguageModel CzechModel =
{
  "cs",
  Unicode_CharOrder,
  Unicode_Char_size,
  CzechFCMLowerBound,
  CzechFCMUpperBound,
  CzechUnicodeCharToOrderIsReduced,

  CzechUnicodeCharToOrder,
  OrderToRatio,
  CzechCompactedLangModel,
  41,
  6,
  0.40506118400512786f,
  27,
  0.0372975153408981f,
  0.9996995366648155f,
};
