/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsSBCharSetProber-generated.h"
#include "../nsLanguageDetector.h"

#include "../nsLanguageDetector-generated.h"

/********* Language model for: Spanish *********/

/**
 * Generated by BuildLangModel.py
 * On: 2023-06-20 02:05:04.575951
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */
static const unsigned char Iso_8859_15_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 14, 10,  8,  0, 17, 15, 19,  5, 23, 27,  7, 12,  4,  2, /* 4X */
   13, 21,  6,  3,  9, 11, 16, 29, 28, 18, 25,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 14, 10,  8,  0, 17, 15, 19,  5, 23, 27,  7, 12,  4,  2, /* 6X */
   13, 21,  6,  3,  9, 11, 16, 29, 28, 18, 25,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM, 36,SYM, 36,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM, 50, 56,SYM,SYM, 50,SYM,SYM,SYM, 58, 58, 59,SYM, /* BX */
   40, 24, 42, 33, 44, 48, 37, 35, 47, 26, 39, 53, 55, 22, 49, 51, /* CX */
   43, 30, 52, 20, 45, 46, 34,SYM, 38, 57, 31, 54, 32, 41, 60, 61, /* DX */
   40, 24, 42, 33, 44, 48, 37, 35, 47, 26, 39, 53, 55, 22, 49, 51, /* EX */
   43, 30, 52, 20, 45, 46, 34,SYM, 38, 57, 31, 54, 32, 41, 62, 63, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_1_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 14, 10,  8,  0, 17, 15, 19,  5, 23, 27,  7, 12,  4,  2, /* 4X */
   13, 21,  6,  3,  9, 11, 16, 29, 28, 18, 25,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 14, 10,  8,  0, 17, 15, 19,  5, 23, 27,  7, 12,  4,  2, /* 6X */
   13, 21,  6,  3,  9, 11, 16, 29, 28, 18, 25,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 56,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   40, 24, 42, 33, 44, 48, 37, 35, 47, 26, 39, 53, 55, 22, 49, 51, /* CX */
   43, 30, 52, 20, 45, 46, 34,SYM, 38, 57, 31, 54, 32, 41, 64, 65, /* DX */
   40, 24, 42, 33, 44, 48, 37, 35, 47, 26, 39, 53, 55, 22, 49, 51, /* EX */
   43, 30, 52, 20, 45, 46, 34,SYM, 38, 57, 31, 54, 32, 41, 66, 67, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1252_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 14, 10,  8,  0, 17, 15, 19,  5, 23, 27,  7, 12,  4,  2, /* 4X */
   13, 21,  6,  3,  9, 11, 16, 29, 28, 18, 25,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 14, 10,  8,  0, 17, 15, 19,  5, 23, 27,  7, 12,  4,  2, /* 6X */
   13, 21,  6,  3,  9, 11, 16, 29, 28, 18, 25,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM, 68,SYM,SYM,SYM,SYM,SYM,SYM, 36,SYM, 58,ILL, 50,ILL, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, 36,SYM, 58,ILL, 50, 69, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 56,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   40, 24, 42, 33, 44, 48, 37, 35, 47, 26, 39, 53, 55, 22, 49, 51, /* CX */
   43, 30, 52, 20, 45, 46, 34,SYM, 38, 57, 31, 54, 32, 41, 70, 71, /* DX */
   40, 24, 42, 33, 44, 48, 37, 35, 47, 26, 39, 53, 55, 22, 49, 51, /* EX */
   43, 30, 52, 20, 45, 46, 34,SYM, 38, 57, 31, 54, 32, 41, 72, 73, /* FX */
};
/*X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const int Unicode_Char_size = 66;
static const unsigned int Unicode_CharOrder[] =
{
  65,  1, 66, 14, 67, 10, 68,  8, 69,  0, 70, 17, 71, 15,72, 19,
  73,  5, 74, 23, 75, 27, 76,  7, 77, 12, 78,  4, 79,  2,80, 13,
  81, 21, 82,  6, 83,  3, 84,  9, 85, 11, 86, 16, 87, 29,88, 28,
  89, 18, 90, 25, 97,  1, 98, 14, 99, 10, 100,  8, 101,  0,102, 17,
  103, 15, 104, 19, 105,  5, 106, 23, 107, 27, 108,  7, 109, 12,110,  4,
  111,  2, 112, 13, 113, 21, 114,  6, 115,  3, 116,  9, 117, 11,118, 16,
  119, 29, 120, 28, 121, 18, 122, 25, 193, 24, 201, 26, 205, 22,209, 30,
  211, 20, 218, 31, 220, 32, 225, 24, 233, 26, 237, 22, 241, 30,243, 20,
  250, 31, 252, 32,
};


/* Model Table:
 * Total considered sequences: 1072 / 1089
 * - Positive sequences: first 491 (0.9950185685466587)
 * - Probable sequences: next 155 (646-491) (0.003982908736845925)
 * - Neutral sequences: last 443 (0.0009985227164953647)
 * - Negative sequences: 17 (off-ratio)
 * Negative sequences: TODO
 */
static const PRUint8 SpanishLangModel[] =
{
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,1,3,3,3,3,1,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,3,3,1,3,2,3,3,3,3,2,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,2,3,1,3,1,3,3,3,2,1,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,1,3,1,3,3,1,2,0,2,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,2,0,3,1,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,3,3,1,3,3,3,3,3,3,1,3,1,0,
  3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,2,3,3,3,3,1,2,0,2,1,
  3,3,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,1,3,2,3,3,1,2,0,1,1,
  3,3,3,3,3,3,3,2,3,2,2,3,3,1,2,2,3,2,3,2,3,2,3,2,3,1,3,1,1,2,0,2,0,
  3,3,3,3,3,3,3,3,2,3,3,3,3,2,3,1,2,2,3,3,3,0,3,1,3,2,3,2,1,3,0,2,1,
  3,3,3,3,3,3,3,3,2,3,3,3,2,2,2,2,1,2,3,3,3,2,3,0,3,1,3,3,1,2,0,3,0,
  3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,1,2,2,3,3,2,3,3,2,2,1,2,0,0,
  3,3,3,3,3,3,2,2,1,2,3,3,3,3,3,2,1,1,3,1,3,0,3,1,3,1,3,1,1,1,0,3,1,
  3,3,3,3,2,3,3,3,2,3,3,3,2,3,1,1,1,1,2,3,3,1,2,1,3,1,3,1,1,1,0,3,0,
  3,3,3,3,3,3,3,3,2,3,3,3,3,1,3,1,2,1,3,1,3,0,3,3,3,1,3,1,0,1,0,2,1,
  3,3,3,2,3,3,3,3,2,3,1,3,3,2,2,2,1,1,2,3,3,0,3,1,2,1,3,1,1,1,0,3,3,
  3,3,3,3,1,3,1,2,2,1,1,3,1,1,1,1,1,0,2,1,3,0,3,1,2,1,3,2,0,1,0,0,0,
  3,3,3,2,1,3,3,3,0,3,1,3,1,1,1,2,0,3,1,1,2,0,3,1,2,1,2,1,1,1,0,3,2,
  3,3,3,3,2,2,2,3,2,2,2,3,2,2,2,2,1,1,1,1,3,1,0,1,2,1,1,1,1,2,0,1,0,
  3,3,3,2,3,3,3,3,1,3,1,3,3,1,1,1,1,1,3,1,2,0,3,1,2,1,2,1,1,2,0,2,1,
  0,0,0,3,3,1,3,3,3,3,3,0,3,3,2,3,3,3,0,0,0,0,0,1,0,1,0,1,2,0,0,0,0,
  1,1,0,1,0,1,1,1,0,1,0,3,0,0,0,0,1,1,0,1,0,1,1,0,0,0,0,0,1,1,0,0,0,
  2,3,3,3,3,1,3,2,3,3,3,0,3,2,2,3,1,3,1,1,1,2,1,1,0,2,0,1,1,0,1,0,0,
  3,3,3,2,1,3,1,1,1,1,1,3,1,1,1,0,1,1,1,1,3,0,1,1,2,0,3,1,0,0,0,1,1,
  1,0,0,3,3,2,3,3,2,3,3,2,3,3,3,3,2,3,1,0,0,2,0,2,0,1,0,1,2,0,1,0,0,
  3,3,3,1,1,3,1,1,1,1,3,3,1,1,1,2,1,1,1,2,3,2,1,1,2,2,1,1,1,1,0,2,0,
  1,3,1,3,3,2,3,3,2,3,3,1,2,3,1,3,1,2,1,0,0,1,0,1,0,1,0,1,3,0,0,0,0,
  3,3,3,3,2,3,3,3,1,2,1,3,3,1,1,1,1,1,3,2,1,1,1,1,1,0,1,1,0,2,0,1,1,
  2,3,3,1,1,3,1,2,1,3,3,3,1,3,1,1,2,2,1,2,1,1,2,1,1,1,1,0,3,1,0,0,0,
  3,3,3,3,3,3,2,2,1,1,1,1,2,1,1,0,1,1,2,3,0,0,0,0,1,0,0,1,0,2,0,0,0,
  2,3,3,0,0,2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2,0,3,0,1,0,1,0,0,0,0,0,0,
  1,2,1,3,3,1,2,3,1,3,2,0,3,2,3,1,0,1,1,0,0,0,0,1,0,1,0,2,0,0,1,0,0,
  2,0,0,0,1,1,1,1,0,1,1,0,0,0,1,0,0,0,0,2,0,0,3,0,0,0,0,1,0,0,0,0,0,
};


const SequenceModel Iso_8859_15SpanishModel =
{
  Iso_8859_15_CharToOrderMap,
  SpanishLangModel,
  33,
  (float)0.9990014772835046,
  PR_TRUE,
  "ISO-8859-15",
  "es"
};

const SequenceModel Iso_8859_1SpanishModel =
{
  Iso_8859_1_CharToOrderMap,
  SpanishLangModel,
  33,
  (float)0.9990014772835046,
  PR_TRUE,
  "ISO-8859-1",
  "es"
};

const SequenceModel Windows_1252SpanishModel =
{
  Windows_1252_CharToOrderMap,
  SpanishLangModel,
  33,
  (float)0.9990014772835046,
  PR_TRUE,
  "WINDOWS-1252",
  "es"
};

const LanguageModel SpanishModel =
{
  "es",
  Unicode_CharOrder,
  66,
  SpanishLangModel,
  33,
  5,
  (float)0.4661881156504941,
  20,
  (float)0.033300671594531456,
  (float)0.9998968926779168,
};
