/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsSBCharSetProber-generated.h"
#include "../nsLanguageDetector.h"

#include "../nsLanguageDetector-generated.h"

/********* Language model for: Italian *********/

/**
 * Generated by BuildLangModel.py
 * On: 2023-07-06 22:42:40.042199
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */
static const unsigned char Iso_8859_1_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 18,  9, 10,  0, 16, 14, 17,  1, 26, 23,  6, 12,  4,  3, /* 4X */
   13, 21,  7,  8,  5, 11, 15, 22, 28, 20, 19,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 18,  9, 10,  0, 16, 14, 17,  1, 26, 23,  6, 12,  4,  3, /* 6X */
   13, 21,  7,  8,  5, 11, 15, 22, 28, 20, 19,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 67,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   25, 33, 43, 54, 40, 52, 37, 42, 24, 30, 45, 49, 31, 36, 58, 59, /* CX */
   50, 41, 27, 35, 55, 66, 32,SYM, 53, 29, 47, 57, 34, 51, 62, 44, /* DX */
   25, 33, 43, 54, 40, 52, 37, 42, 24, 30, 45, 49, 31, 36, 58, 59, /* EX */
   50, 41, 27, 35, 55, 66, 32,SYM, 53, 29, 47, 57, 34, 51, 62, 68, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_3_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 18,  9, 10,  0, 16, 14, 17,  1, 26, 23,  6, 12,  4,  3, /* 4X */
   13, 21,  7,  8,  5, 11, 15, 22, 28, 20, 19,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 18,  9, 10,  0, 16, 14, 17,  1, 26, 23,  6, 12,  4,  3, /* 6X */
   13, 21,  7,  8,  5, 11, 15, 22, 28, 20, 19,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM, 69,SYM,SYM,SYM,ILL, 70,SYM,SYM, 63, 46, 56, 71,SYM,ILL, 60, /* AX */
  SYM, 72,SYM,SYM,SYM,SYM, 73,SYM,SYM, 39, 46, 56, 74,SYM,ILL, 60, /* BX */
   25, 33, 43,ILL, 40, 75, 76, 42, 24, 30, 45, 49, 31, 36, 58, 59, /* CX */
  ILL, 41, 27, 35, 55, 77, 32,SYM, 65, 29, 47, 57, 34, 64, 78, 44, /* DX */
   25, 33, 43,ILL, 40, 79, 80, 42, 24, 30, 45, 49, 31, 36, 58, 59, /* EX */
  ILL, 41, 27, 35, 55, 81, 32,SYM, 65, 29, 47, 57, 34, 64, 82,SYM, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_9_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 18,  9, 10,  0, 16, 14, 17,  1, 26, 23,  6, 12,  4,  3, /* 4X */
   13, 21,  7,  8,  5, 11, 15, 22, 28, 20, 19,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 18,  9, 10,  0, 16, 14, 17,  1, 26, 23,  6, 12,  4,  3, /* 6X */
   13, 21,  7,  8,  5, 11, 15, 22, 28, 20, 19,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 83,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   25, 33, 43, 54, 40, 52, 37, 42, 24, 30, 45, 49, 31, 36, 58, 59, /* CX */
   56, 41, 27, 35, 55, 66, 32,SYM, 53, 29, 47, 57, 34, 63, 46, 44, /* DX */
   25, 33, 43, 54, 40, 52, 37, 42, 24, 30, 45, 49, 31, 36, 58, 59, /* EX */
   56, 41, 27, 35, 55, 66, 32,SYM, 53, 29, 47, 57, 34, 39, 46, 84, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_15_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 18,  9, 10,  0, 16, 14, 17,  1, 26, 23,  6, 12,  4,  3, /* 4X */
   13, 21,  7,  8,  5, 11, 15, 22, 28, 20, 19,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 18,  9, 10,  0, 16, 14, 17,  1, 26, 23,  6, 12,  4,  3, /* 6X */
   13, 21,  7,  8,  5, 11, 15, 22, 28, 20, 19,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM, 38,SYM, 38,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM, 48, 85,SYM,SYM, 48,SYM,SYM,SYM, 61, 61, 86,SYM, /* BX */
   25, 33, 43, 54, 40, 52, 37, 42, 24, 30, 45, 49, 31, 36, 58, 59, /* CX */
   50, 41, 27, 35, 55, 66, 32,SYM, 53, 29, 47, 57, 34, 51, 62, 44, /* DX */
   25, 33, 43, 54, 40, 52, 37, 42, 24, 30, 45, 49, 31, 36, 58, 59, /* EX */
   50, 41, 27, 35, 55, 66, 32,SYM, 53, 29, 47, 57, 34, 51, 62, 87, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1252_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  2, 18,  9, 10,  0, 16, 14, 17,  1, 26, 23,  6, 12,  4,  3, /* 4X */
   13, 21,  7,  8,  5, 11, 15, 22, 28, 20, 19,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  2, 18,  9, 10,  0, 16, 14, 17,  1, 26, 23,  6, 12,  4,  3, /* 6X */
   13, 21,  7,  8,  5, 11, 15, 22, 28, 20, 19,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM, 88,SYM,SYM,SYM,SYM,SYM,SYM, 38,SYM, 61,ILL, 48,ILL, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, 38,SYM, 61,ILL, 48, 89, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 90,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   25, 33, 43, 54, 40, 52, 37, 42, 24, 30, 45, 49, 31, 36, 58, 59, /* CX */
   50, 41, 27, 35, 55, 66, 32,SYM, 53, 29, 47, 57, 34, 51, 62, 44, /* DX */
   25, 33, 43, 54, 40, 52, 37, 42, 24, 30, 45, 49, 31, 36, 58, 59, /* EX */
   50, 41, 27, 35, 55, 66, 32,SYM, 53, 29, 47, 57, 34, 51, 62, 91, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

#define Unicode_Char_size    72

static const unsigned int Unicode_CharOrder[] =
{
  65,  2, 66, 18, 67,  9, 68, 10, 69,  0, 70, 16, 71, 14, 72, 17,
  73,  1, 74, 26, 75, 23, 76,  6, 77, 12, 78,  4, 79,  3, 80, 13,
  81, 21, 82,  7, 83,  8, 84,  5, 85, 11, 86, 15, 87, 22, 88, 28,
  89, 20, 90, 19, 97,  2, 98, 18, 99,  9, 100, 10, 101,  0, 102, 16,
  103, 14, 104, 17, 105,  1, 106, 26, 107, 23, 108,  6, 109, 12, 110,  4,
  111,  3, 112, 13, 113, 21, 114,  7, 115,  8, 116,  5, 117, 11, 118, 15,
  119, 22, 120, 28, 121, 20, 122, 19, 192, 25, 193, 33, 200, 24, 201, 30,
  204, 31, 210, 27, 211, 35, 214, 32, 217, 29, 220, 34, 224, 25, 225, 33,
  232, 24, 233, 30, 236, 31, 242, 27, 243, 35, 246, 32, 249, 29, 252, 34,
};

static const float OrderToRatio[] =
{
  0.112850734,  0.112850734,  0.112279451,  0.112279451,  0.104513961,  0.104513961,  0.086183160,  0.086183160, 
  0.073169286,  0.073169286,  0.067161550,  0.067161550,  0.065351839,  0.065351839,  0.065114008,  0.065114008, 
  0.051429084,  0.051429084,  0.041686791,  0.041686791,  0.039220909,  0.039220909,  0.030505314,  0.030505314, 
  0.027946983,  0.027946983,  0.026404374,  0.026404374,  0.019452144,  0.019452144,  0.014518430,  0.014518430, 
  0.011975710,  0.011975710,  0.011581765,  0.011581765,  0.011123665,  0.011123665,  0.008754868,  0.008754868, 
  0.002916663,  0.002916663,  0.002873244,  0.002873244,  0.002524669,  0.002524669,  0.002502715,  0.002502715, 
  0.001549927,  0.001549927,  0.001515533,  0.001515533,  0.001176959,  0.001176959,  0.001076704,  0.001076704, 
  0.000793746,  0.000793746,  0.000646657,  0.000646657,  0.000384920,  0.000384920,  0.000367602,  0.000367602, 
  0.000074886,  0.000074886,  0.000050249,  0.000050249,  0.000043419,  0.000043419,  0.000037809,  0.000037809, 
};


/* Model Table:
 * Number of web pages processed for this model: 558
 * Number of characters consumed for this model: 4099548
 * Total considered sequences: 1329 / 1296
 *
 * - Positive sequences: first 388 (0.9950063065539928)
 * - Probable sequences: next 231 (619-388) (0.003995256217321663)
 * - Neutral sequences: last 677 (0.0009984372286855336)
 * - Negative sequences: -33 (off-ratio, TODO)
 */


#define ItalianUnicodeAlphabetWidth         36
#define ItalianUnicodeCharToOrderIsReduced  0


#define ItalianFCMLowerBound  97
#define ItalianFCMUpperBound  252


static const PRUint8 ItalianUnicodeCharToOrder[] =
{
  3,19,10,11,1,17,15,18,2,27,24,7,13,5,4,14,22,8,9,6,
  12,16,23,29,21,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,26,34,0,0,0,0,0,0,25,31,0,0,32,
  0,0,0,0,0,28,36,0,0,33,0,0,30,0,0,35,
};

static const PRUint8 ItalianCompactedLangModel[] =
{
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,0,2,2,3,0,0,1,1,0,0,1,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,2,3,2,3,2,3,2,3,3,3,1,0,0,1,0,2,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,0,0,3,0,3,0,1,0,0,0,1,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,2,1,3,0,3,0,0,0,0,0,0,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,2,2,3,3,3,2,3,3,3,3,2,3,1,1,2,3,2,1,3,2,1,2,0,1,
  0,3,3,3,3,3,3,3,3,3,3,2,3,3,3,2,3,2,3,3,3,3,1,3,2,1,3,1,3,1,2,2,2,1,1,1,1,
  0,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,2,3,2,3,2,2,3,1,2,2,2,1,1,2,2,1,2,1,1,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,2,3,1,3,1,1,2,3,1,1,1,2,
  0,3,3,3,3,3,3,3,3,3,3,2,3,3,3,2,3,3,3,3,2,3,3,3,3,1,0,1,3,1,2,2,3,1,1,1,1,
  0,3,3,3,3,3,3,3,3,3,3,2,3,2,2,2,1,2,3,3,2,3,3,2,3,1,1,1,3,1,0,2,3,0,1,0,1,
  0,3,3,3,3,3,2,3,3,3,2,3,3,3,2,3,2,2,2,3,2,3,1,3,2,1,2,2,2,1,1,2,2,1,1,1,1,
  0,3,3,3,3,3,3,3,3,3,3,3,1,3,3,3,2,3,2,3,3,2,1,2,3,1,0,2,3,2,0,2,2,0,1,0,0,
  0,3,3,3,3,2,2,3,2,3,3,3,3,3,3,2,2,2,1,3,1,3,1,2,2,1,1,1,2,1,1,2,0,1,1,2,1,
  0,3,3,3,3,2,3,3,3,3,2,2,3,2,3,1,1,2,3,2,2,2,0,2,2,1,1,1,2,1,1,1,2,0,1,0,1,
  0,3,3,3,3,3,3,3,3,3,2,2,3,3,2,3,1,2,3,2,1,3,1,2,2,1,1,2,2,1,1,2,1,2,0,1,1,
  0,3,3,3,3,1,1,2,3,2,1,2,3,1,1,1,3,2,1,1,1,2,0,0,1,0,1,1,2,0,1,1,1,1,1,0,0,
  0,3,3,3,3,1,3,3,3,2,2,1,3,2,1,2,1,3,1,2,1,2,0,2,1,2,1,1,1,1,1,1,0,1,1,2,0,
  0,3,3,3,3,3,3,3,3,2,1,2,3,3,2,1,2,2,1,2,1,3,1,2,1,1,0,1,1,1,0,3,1,1,1,1,1,
  0,3,3,3,3,3,2,3,3,3,2,2,3,2,2,1,1,2,2,3,1,3,1,1,1,1,1,3,1,1,2,2,2,1,1,1,1,
  0,3,3,3,3,1,1,2,1,1,1,1,3,1,1,2,1,1,2,1,3,2,1,2,2,0,1,1,2,1,0,1,0,0,1,1,1,
  0,3,2,3,3,3,3,3,2,3,3,3,2,3,2,2,1,1,2,2,1,1,1,2,2,1,0,1,0,1,0,1,0,0,1,0,0,
  0,1,1,1,1,0,1,2,1,1,0,1,3,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,3,3,3,3,3,2,2,3,3,2,2,2,1,1,1,1,2,3,2,1,2,0,3,2,0,0,0,0,1,0,1,0,1,1,1,1,
  0,3,3,3,3,3,2,3,3,3,1,2,3,2,1,2,2,2,2,2,1,3,1,2,2,1,1,2,1,0,0,1,0,2,1,1,1,
  0,0,1,1,0,1,1,1,2,2,1,1,1,1,0,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,3,3,3,3,1,1,1,2,2,2,2,3,1,2,1,1,1,1,1,1,1,0,1,1,0,0,1,1,0,0,1,0,3,1,1,1,
  0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,
  0,3,3,2,2,1,3,2,1,2,2,0,1,2,2,1,3,2,2,1,1,2,1,1,0,0,0,1,0,2,0,1,0,0,0,0,0,
  0,0,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,2,1,2,2,2,2,2,2,1,2,2,0,2,2,1,1,1,1,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,
  0,1,0,1,0,0,1,0,0,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,1,0,0,1,1,2,3,1,1,1,0,1,1,1,1,1,1,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,
  0,1,1,0,0,2,1,2,2,1,1,1,0,1,1,1,0,1,1,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,
  0,1,0,0,0,2,1,2,2,1,1,1,0,1,0,1,0,1,2,1,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,
  0,0,0,0,0,2,1,1,1,1,1,1,0,1,1,1,1,1,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,
};


const SequenceModel Iso_8859_1ItalianModel =
{
  Iso_8859_1_CharToOrderMap,
  ItalianFCMLowerBound,
  ItalianFCMUpperBound,
  ItalianUnicodeCharToOrder,
  ItalianCompactedLangModel,
  36,
  (float)0.9990015627713145,
  PR_TRUE,
  "ISO-8859-1",
  "it"
};

const SequenceModel Iso_8859_3ItalianModel =
{
  Iso_8859_3_CharToOrderMap,
  ItalianFCMLowerBound,
  ItalianFCMUpperBound,
  ItalianUnicodeCharToOrder,
  ItalianCompactedLangModel,
  36,
  (float)0.9990015627713145,
  PR_TRUE,
  "ISO-8859-3",
  "it"
};

const SequenceModel Iso_8859_9ItalianModel =
{
  Iso_8859_9_CharToOrderMap,
  ItalianFCMLowerBound,
  ItalianFCMUpperBound,
  ItalianUnicodeCharToOrder,
  ItalianCompactedLangModel,
  36,
  (float)0.9990015627713145,
  PR_TRUE,
  "ISO-8859-9",
  "it"
};

const SequenceModel Iso_8859_15ItalianModel =
{
  Iso_8859_15_CharToOrderMap,
  ItalianFCMLowerBound,
  ItalianFCMUpperBound,
  ItalianUnicodeCharToOrder,
  ItalianCompactedLangModel,
  36,
  (float)0.9990015627713145,
  PR_TRUE,
  "ISO-8859-15",
  "it"
};

const SequenceModel Windows_1252ItalianModel =
{
  Windows_1252_CharToOrderMap,
  ItalianFCMLowerBound,
  ItalianFCMUpperBound,
  ItalianUnicodeCharToOrder,
  ItalianCompactedLangModel,
  36,
  (float)0.9990015627713145,
  PR_TRUE,
  "WINDOWS-1252",
  "it"
};

const LanguageModel ItalianModel =
{
  "it",
  Unicode_CharOrder,
  72,
  ItalianFCMLowerBound,
  ItalianFCMUpperBound,
  ItalianUnicodeCharToOrderIsReduced,

  ItalianUnicodeCharToOrder,
  OrderToRatio,
  ItalianCompactedLangModel,
  36,
  4,
  (float)0.4158273058395706,
  17,
  (float)0.03841423493516846,
  (float)0.9997597296092153,
};
