/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsSBCharSetProber-generated.h"
#include "../nsLanguageDetector.h"

#include "../nsLanguageDetector-generated.h"

/********* Language model for: French *********/

/**
 * Generated by BuildLangModel.py
 * On: 2023-07-06 22:51:53.308084
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */
static const unsigned char Iso_8859_15_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 18, 11, 10,  0, 19, 16, 17,  4, 25, 26,  7, 12,  3,  8, /* 4X */
   13, 20,  5,  2,  6,  9, 15, 27, 22, 21, 28,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 18, 11, 10,  0, 19, 16, 17,  4, 25, 26,  7, 12,  3,  8, /* 6X */
   13, 20,  5,  2,  6,  9, 15, 27, 22, 21, 28,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM, 46,SYM, 46,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM, 56, 57,SYM,SYM, 56,SYM,SYM,SYM, 36, 36, 61,SYM, /* BX */
   23, 38, 33, 44, 45, 49, 52, 30, 24, 14, 29, 40, 54, 42, 32, 37, /* CX */
   59, 48, 55, 43, 31, 60, 39,SYM, 47, 34, 50, 35, 41, 53, 62, 51, /* DX */
   23, 38, 33, 44, 45, 49, 52, 30, 24, 14, 29, 40, 54, 42, 32, 37, /* EX */
   59, 48, 55, 43, 31, 60, 39,SYM, 47, 34, 50, 35, 41, 53, 63, 61, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_1_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 18, 11, 10,  0, 19, 16, 17,  4, 25, 26,  7, 12,  3,  8, /* 4X */
   13, 20,  5,  2,  6,  9, 15, 27, 22, 21, 28,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 18, 11, 10,  0, 19, 16, 17,  4, 25, 26,  7, 12,  3,  8, /* 6X */
   13, 20,  5,  2,  6,  9, 15, 27, 22, 21, 28,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 57,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   23, 38, 33, 44, 45, 49, 52, 30, 24, 14, 29, 40, 54, 42, 32, 37, /* CX */
   59, 48, 55, 43, 31, 60, 39,SYM, 47, 34, 50, 35, 41, 53, 64, 51, /* DX */
   23, 38, 33, 44, 45, 49, 52, 30, 24, 14, 29, 40, 54, 42, 32, 37, /* EX */
   59, 48, 55, 43, 31, 60, 39,SYM, 47, 34, 50, 35, 41, 53, 65, 61, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Windows_1252_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM,  1, 18, 11, 10,  0, 19, 16, 17,  4, 25, 26,  7, 12,  3,  8, /* 4X */
   13, 20,  5,  2,  6,  9, 15, 27, 22, 21, 28,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM,  1, 18, 11, 10,  0, 19, 16, 17,  4, 25, 26,  7, 12,  3,  8, /* 6X */
   13, 20,  5,  2,  6,  9, 15, 27, 22, 21, 28,SYM,SYM,SYM,SYM,CTR, /* 7X */
  SYM,ILL,SYM, 58,SYM,SYM,SYM,SYM,SYM,SYM, 46,SYM, 36,ILL, 56,ILL, /* 8X */
  ILL,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, 46,SYM, 36,ILL, 56, 61, /* 9X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* AX */
  SYM,SYM,SYM,SYM,SYM, 57,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* BX */
   23, 38, 33, 44, 45, 49, 52, 30, 24, 14, 29, 40, 54, 42, 32, 37, /* CX */
   59, 48, 55, 43, 31, 60, 39,SYM, 47, 34, 50, 35, 41, 53, 66, 51, /* DX */
   23, 38, 33, 44, 45, 49, 52, 30, 24, 14, 29, 40, 54, 42, 32, 37, /* EX */
   59, 48, 55, 43, 31, 60, 39,SYM, 47, 34, 50, 35, 41, 53, 67, 61, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

#define Unicode_Char_size    76

static const unsigned int Unicode_CharOrder[] =
{
  65,  1, 66, 18, 67, 11, 68, 10, 69,  0, 70, 19, 71, 16, 72, 17,
  73,  4, 74, 25, 75, 26, 76,  7, 77, 12, 78,  3, 79,  8, 80, 13,
  81, 20, 82,  5, 83,  2, 84,  6, 85,  9, 86, 15, 87, 27, 88, 22,
  89, 21, 90, 28, 97,  1, 98, 18, 99, 11, 100, 10, 101,  0, 102, 19,
  103, 16, 104, 17, 105,  4, 106, 25, 107, 26, 108,  7, 109, 12, 110,  3,
  111,  8, 112, 13, 113, 20, 114,  5, 115,  2, 116,  6, 117,  9, 118, 15,
  119, 27, 120, 22, 121, 21, 122, 28, 192, 23, 194, 33, 199, 30, 200, 24,
  201, 14, 202, 29, 206, 32, 207, 37, 212, 31, 217, 34, 219, 35, 224, 23,
  226, 33, 231, 30, 232, 24, 233, 14, 234, 29, 238, 32, 239, 37, 244, 31,
  249, 34, 251, 35, 338, 36, 339, 36,
};

static const float OrderToRatio[] =
{
  0.140128282,  0.140128282,  0.079217003,  0.079217003,  0.076138327,  0.076138327,  0.073825346,  0.073825346, 
  0.072919895,  0.072919895,  0.069659701,  0.069659701,  0.068332371,  0.068332371,  0.058080083,  0.058080083, 
  0.055560670,  0.055560670,  0.052128451,  0.052128451,  0.040587746,  0.040587746,  0.035318761,  0.035318761, 
  0.028922233,  0.028922233,  0.028214672,  0.028214672,  0.022894197,  0.022894197,  0.012577370,  0.012577370, 
  0.012440461,  0.012440461,  0.012020005,  0.012020005,  0.011283733,  0.011283733,  0.011215397,  0.011215397, 
  0.008282884,  0.008282884,  0.004908086,  0.004908086,  0.004148798,  0.004148798,  0.003952095,  0.003952095, 
  0.003660243,  0.003660243,  0.003628211,  0.003628211,  0.002719912,  0.002719912,  0.002234443,  0.002234443, 
  0.001182591,  0.001182591,  0.000957889,  0.000957889,  0.000492588,  0.000492588,  0.000451539,  0.000451539, 
  0.000395779,  0.000395779,  0.000374899,  0.000374899,  0.000213313,  0.000213313,  0.000205957,  0.000205957, 
  0.000194568,  0.000194568,  0.000142841,  0.000142841, 
};


/* Model Table:
 * Number of web pages processed for this model: 412
 * Number of characters consumed for this model: 4214474
 * Total considered sequences: 1330 / 1444
 *
 * - Positive sequences: first 493 (0.9950115208197672)
 * - Probable sequences: next 212 (705-493) (0.0039908429757585795)
 * - Neutral sequences: last 739 (0.0009976362044742393)
 * - Negative sequences: 114 (off-ratio, TODO)
 */


#define FrenchUnicodeAlphabetWidth         38
#define FrenchUnicodeCharToOrderIsReduced  0


#define FrenchFCMLowerBound  97
#define FrenchFCMUpperBound  339


static const PRUint8 FrenchUnicodeCharToOrder[] =
{
  2,19,12,11,1,20,17,18,5,26,27,8,13,4,9,14,21,6,3,7,
  10,16,28,23,22,29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,24,0,34,0,0,0,0,31,25,15,30,0,0,
  0,33,38,0,0,0,0,32,0,0,0,0,35,0,36,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,37,
};

static const PRUint8 FrenchCompactedLangModel[] =
{
  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,3,3,3,3,3,3,3,1,0,3,3,3,3,0,3,1,0,1,0,1,0,1,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,1,3,3,3,3,0,3,1,3,0,0,0,0,3,
  0,3,3,3,3,3,2,3,3,3,3,2,3,3,3,3,3,2,3,3,3,3,3,1,1,3,1,3,3,2,0,0,0,1,1,0,2,2,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,2,1,3,3,3,2,3,2,3,1,1,1,0,0,2,1,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,2,3,1,3,2,3,2,3,1,1,1,0,1,1,0,0,1,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,3,2,3,3,2,3,2,3,1,3,0,2,1,0,
  0,3,3,3,3,3,3,3,3,3,3,2,3,3,2,3,3,2,3,3,2,0,3,1,1,3,1,2,3,3,3,0,3,1,2,1,0,0,1,
  0,3,3,3,2,3,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,3,1,3,2,2,1,1,2,0,2,0,1,0,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,0,3,3,3,3,3,1,1,0,2,0,3,3,0,3,
  0,3,3,3,3,3,3,3,3,3,1,3,3,3,3,3,3,3,3,3,3,2,3,3,0,2,3,3,2,3,3,1,0,1,0,0,0,0,2,
  0,3,3,3,3,3,3,2,3,3,3,3,3,3,2,3,2,3,3,3,2,1,3,1,0,3,3,1,3,2,1,0,1,1,1,0,2,0,0,
  0,3,3,3,2,3,3,3,3,3,3,3,3,2,2,3,1,2,3,2,2,3,3,1,0,3,1,3,1,2,2,0,3,1,2,0,0,2,0,
  0,3,3,3,3,3,2,3,2,3,3,2,3,3,3,3,1,1,1,3,2,1,3,1,0,3,1,2,3,1,3,0,1,1,2,0,1,1,0,
  0,3,3,3,2,3,3,3,3,3,3,2,2,2,3,3,1,2,3,2,2,1,2,0,0,3,1,2,1,1,2,2,2,1,2,0,0,1,0,
  0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,1,1,0,1,3,2,0,2,0,1,0,0,3,0,0,0,0,
  0,3,3,2,1,3,3,1,2,3,3,2,1,1,1,3,0,1,1,1,3,1,2,0,0,3,1,2,1,1,2,0,1,1,1,0,0,1,0,
  0,3,3,3,3,3,3,3,3,3,3,2,1,3,2,3,1,3,3,2,2,1,3,1,1,3,1,2,2,1,1,0,1,1,1,0,0,0,0,
  0,3,3,3,3,3,3,3,3,3,3,2,2,3,1,3,1,1,1,2,2,1,3,1,0,3,1,2,3,2,1,0,3,0,2,0,1,2,0,
  0,3,3,3,3,3,3,3,3,3,3,2,2,2,1,3,2,1,2,3,1,1,3,1,1,2,3,2,1,1,2,0,0,1,2,0,1,2,0,
  0,3,3,3,2,3,3,3,3,3,3,2,2,2,1,3,1,2,1,2,3,1,1,1,0,2,1,2,1,1,2,0,0,0,1,0,1,1,0,
  0,1,2,0,1,1,1,1,1,1,3,1,1,1,1,0,1,0,0,1,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,
  0,3,3,3,3,2,3,3,3,3,2,3,3,3,3,3,2,2,1,2,1,1,1,1,0,1,1,1,2,1,0,1,0,0,1,0,0,0,1,
  0,3,3,1,0,3,1,3,1,2,3,1,3,1,3,2,3,1,2,1,2,2,2,3,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,
  0,0,0,1,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,3,3,0,3,3,3,1,0,3,3,3,1,0,3,3,0,2,1,2,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,
  0,3,3,1,1,3,2,1,1,3,3,1,1,1,2,2,1,1,1,1,1,0,1,0,3,0,1,1,1,1,0,0,0,0,0,0,0,0,0,
  0,3,3,3,2,3,3,2,3,3,3,2,1,3,1,2,1,2,3,1,1,1,3,1,0,0,1,2,2,0,0,1,0,0,1,1,0,0,0,
  0,3,3,3,3,3,2,2,2,3,2,2,2,1,1,1,1,1,3,2,1,0,2,1,0,1,1,2,3,1,0,0,0,0,0,0,0,0,0,
  0,3,3,1,2,3,1,1,2,3,2,1,1,2,1,2,1,1,2,2,1,1,2,0,1,1,1,2,1,3,0,0,0,0,0,0,0,0,0,
  0,0,0,1,2,0,1,3,2,0,0,0,2,3,1,0,2,0,0,0,0,2,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,
  0,0,3,0,0,0,0,0,1,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,1,2,0,1,3,3,0,0,1,0,3,2,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,1,3,0,1,3,3,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,
  0,1,0,1,2,0,1,3,2,1,0,0,3,2,1,0,0,3,0,2,0,2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,1,0,2,3,2,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,0,0,0,0,2,0,1,0,0,3,1,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
  0,2,1,2,2,0,1,2,1,2,0,2,2,1,0,0,1,1,0,1,1,2,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,
};


const SequenceModel Iso_8859_15FrenchModel =
{
  Iso_8859_15_CharToOrderMap,
  FrenchFCMLowerBound,
  FrenchFCMUpperBound,
  FrenchUnicodeCharToOrder,
  FrenchCompactedLangModel,
  38,
  0.9990023637955258f,
  PR_TRUE,
  "ISO-8859-15",
  "fr"
};

const SequenceModel Iso_8859_1FrenchModel =
{
  Iso_8859_1_CharToOrderMap,
  FrenchFCMLowerBound,
  FrenchFCMUpperBound,
  FrenchUnicodeCharToOrder,
  FrenchCompactedLangModel,
  38,
  0.9990023637955258f,
  PR_TRUE,
  "ISO-8859-1",
  "fr"
};

const SequenceModel Windows_1252FrenchModel =
{
  Windows_1252_CharToOrderMap,
  FrenchFCMLowerBound,
  FrenchFCMUpperBound,
  FrenchUnicodeCharToOrder,
  FrenchCompactedLangModel,
  38,
  0.9990023637955258f,
  PR_TRUE,
  "WINDOWS-1252",
  "fr"
};

const LanguageModel FrenchModel =
{
  "fr",
  Unicode_CharOrder,
  Unicode_Char_size,
  FrenchFCMLowerBound,
  FrenchFCMUpperBound,
  FrenchUnicodeCharToOrderIsReduced,

  FrenchUnicodeCharToOrder,
  OrderToRatio,
  FrenchCompactedLangModel,
  38,
  5,
  0.44222885228382f,
  19,
  0.038146634669000215f,
  0.9996113393984634f,
};
