/* -*- Mode: C++; tab-width: 2; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mozilla Communicator client code.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1998
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "../nsSBCharSetProber.h"
#include "../nsSBCharSetProber-generated.h"
#include "../nsLanguageDetector.h"

#include "../nsLanguageDetector-generated.h"

/********* Language model for: Belarusian *********/

/**
 * Generated by BuildLangModel.py
 * On: 2023-07-08 23:28:29.835083
 **/

/* Character Mapping Table:
 * ILL: illegal character.
 * CTR: control character specific to the charset.
 * RET: carriage/return.
 * SYM: symbol (punctuation) that does not belong to word.
 * NUM: 0 - 9.
 * IRR: irrelevant character (which does belong to a word)
 *
 * Other characters are ordered by probabilities
 * (0 is the most common character in the language).
 *
 * Orders are generic to a language. So the codepoint with order X in
 * CHARSET1 maps to the same character as the codepoint with the same
 * order X in CHARSET2 for the same language.
 * As such, it is possible to get missing order. For instance the
 * ligature of 'o' and 'e' exists in ISO-8859-15 but not in ISO-8859-1
 * even though they are both used for French. Same for the euro sign.
 */



#define IRR                     (-1)

#define BelarusianOrderWidth        40


static const unsigned char Windows_1251_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM, 32,249,249,249, 31,249,249,249, 29,249,249,249,249, 36, 34, /* 4X */
  249,249, 35, 37, 38,249,249,249,249,249,249,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM, 32,249,249,249, 31,249,249,249, 29,249,249,249,249, 36, 34, /* 6X */
  249,249, 35, 37, 38,249,249,249,249,249,249,SYM,SYM,SYM,SYM,CTR, /* 7X */
  249,249,SYM,249,SYM,SYM,SYM,SYM,SYM,SYM,249,SYM,249,249,249,249, /* 8X */
  249,SYM,SYM,SYM,SYM,SYM,SYM,SYM,ILL,SYM,249,SYM,249,249,249,249, /* 9X */
  SYM, 19, 19,249,SYM,249,SYM,SYM, 39,SYM,249,SYM,SYM,SYM,SYM,249, /* AX */
  SYM,SYM,  2,  2,249,SYM,SYM,SYM, 39,SYM,249,SYM,249,249,249,249, /* BX */
    0, 21, 14, 20, 11,  9, 28, 17,249, 23,  6,  7, 13,  1, 12, 15, /* CX */
    3,  4,  8, 16, 33, 26, 18, 24, 27,249,249,  5, 25, 22, 30, 10, /* DX */
    0, 21, 14, 20, 11,  9, 28, 17,249, 23,  6,  7, 13,  1, 12, 15, /* EX */
    3,  4,  8, 16, 33, 26, 18, 24, 27,249,249,  5, 25, 22, 30, 10, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

static const unsigned char Iso_8859_5_CharToOrderMap[] =
{
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,RET,CTR,CTR,RET,CTR,CTR, /* 0X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 1X */
  SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM,SYM, /* 2X */
  NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,SYM,SYM,SYM,SYM,SYM,SYM, /* 3X */
  SYM, 32,249,249,249, 31,249,249,249, 29,249,249,249,249, 36, 34, /* 4X */
  249,249, 35, 37, 38,249,249,249,249,249,249,SYM,SYM,SYM,SYM,SYM, /* 5X */
  SYM, 32,249,249,249, 31,249,249,249, 29,249,249,249,249, 36, 34, /* 6X */
  249,249, 35, 37, 38,249,249,249,249,249,249,SYM,SYM,SYM,SYM,CTR, /* 7X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 8X */
  CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR,CTR, /* 9X */
  SYM, 39,249,249,249,249,  2,249,249,249,249,249,249,SYM, 19,249, /* AX */
    0, 21, 14, 20, 11,  9, 28, 17,249, 23,  6,  7, 13,  1, 12, 15, /* BX */
    3,  4,  8, 16, 33, 26, 18, 24, 27,249,249,  5, 25, 22, 30, 10, /* CX */
    0, 21, 14, 20, 11,  9, 28, 17,249, 23,  6,  7, 13,  1, 12, 15, /* DX */
    3,  4,  8, 16, 33, 26, 18, 24, 27,249,249,  5, 25, 22, 30, 10, /* EX */
  SYM, 39,249,249,249,249,  2,249,249,249,249,249,249,SYM, 19,249, /* FX */
};
/* X0  X1  X2  X3  X4  X5  X6  X7  X8  X9  XA  XB  XC  XD  XE  XF */

#define Unicode_Char_size    80

static const PRUint32 Unicode_CharOrder[] =
{
    65, 32,   69, 31,   73, 29,   78, 36,   79, 34,   82, 35,   83, 37,   84, 38,
    97, 32,  101, 31,  105, 29,  110, 36,  111, 34,  114, 35,  115, 37,  116, 38,
  1025, 39, 1030,  2, 1038, 19, 1040,  0, 1041, 21, 1042, 14, 1043, 20, 1044, 11,
  1045,  9, 1046, 28, 1047, 17, 1049, 23, 1050,  6, 1051,  7, 1052, 13, 1053,  1,
  1054, 12, 1055, 15, 1056,  3, 1057,  4, 1058,  8, 1059, 16, 1060, 33, 1061, 26,
  1062, 18, 1063, 24, 1064, 27, 1067,  5, 1068, 25, 1069, 22, 1070, 30, 1071, 10,
  1072,  0, 1073, 21, 1074, 14, 1075, 20, 1076, 11, 1077,  9, 1078, 28, 1079, 17,
  1081, 23, 1082,  6, 1083,  7, 1084, 13, 1085,  1, 1086, 12, 1087, 15, 1088,  3,
  1089,  4, 1090,  8, 1091, 16, 1092, 33, 1093, 26, 1094, 18, 1095, 24, 1096, 27,
  1099,  5, 1100, 25, 1101, 22, 1102, 30, 1103, 10, 1105, 39, 1110,  2, 1118, 19,
};

static const float OrderToRatio[] =
{
  0.154363849f,  0.066316992f,  0.055497512f,  0.049642880f,  0.043778500f,  0.043313259f,  0.038374000f,  0.037946534f, 
  0.034971085f,  0.034837289f,  0.031555497f,  0.031065641f,  0.029964075f,  0.029312396f,  0.028568107f,  0.027023477f, 
  0.025978694f,  0.022874080f,  0.021042116f,  0.020359486f,  0.019817964f,  0.013932868f,  0.013080616f,  0.011852565f, 
  0.011613242f,  0.010693483f,  0.010274546f,  0.008127466f,  0.005703532f,  0.005282889f,  0.005262418f,  0.005236097f, 
  0.004846406f,  0.004248343f,  0.003818439f,  0.003774328f,  0.003694879f,  0.003513803f,  0.003503079f,  0.003169441f, 
  0    /* value slot for out-of-bounds index values; range: 0..freq_count(40) */
};


/* Model Table:
 * Number of web pages processed for this model: 1453
 * Number of characters consumed for this model: 4103247
 * Total considered sequences: 1885 / 1600
 *
 * - Positive sequences: first 942 (0.9950044996073815)
 * - Probable sequences: next 299 (1241-942) (0.003996107751846334)
 * - Neutral sequences: last 359 (0.000999392640772201)
 * - Negative sequences: -285 (off-ratio, TODO)
 */
#define BelarusianUnicodeCharToOrderIsReduced  0


#define BelarusianFCMLowerBound  65
#define BelarusianFCMUpperBound  1118


static const PRInt16 BelarusianUnicodeCharToOrder[] =
{
  32,IRR,IRR,IRR,31,IRR,IRR,IRR,29,IRR,IRR,IRR,IRR,36,34,IRR,IRR,35,37,38,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,32,IRR,IRR,IRR,31,IRR,IRR,IRR,
  29,IRR,IRR,IRR,IRR,36,34,IRR,IRR,35,37,38,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,IRR,
  39,IRR,IRR,IRR,IRR,2,IRR,IRR,IRR,IRR,IRR,IRR,IRR,19,IRR,0,21,14,20,11,
  9,28,17,IRR,23,6,7,13,1,12,15,3,4,8,16,33,26,18,24,27,
  IRR,IRR,5,25,22,30,10,0,21,14,20,11,9,28,17,IRR,23,6,7,13,
  1,12,15,3,4,8,16,33,26,18,24,27,IRR,IRR,5,25,22,30,10,IRR,
  39,IRR,IRR,IRR,IRR,2,IRR,IRR,IRR,IRR,IRR,IRR,IRR,19,
};



#define BelarusianUnicodeCharToOrderFirstTableChunkSize    52
#define BelarusianUnicodeCharToOrderSecondTableChunkOffset 960
#define BelarusianUnicodeCharToOrderSecondTableChunkSize   94


static const PRInt16 BelarusianUnicodeCharToOrder2[] =
{
  39,IRR,IRR,IRR,IRR,2,IRR,IRR,IRR,IRR,IRR,IRR,IRR,19,IRR,0,21,14,20,11,
  9,28,17,IRR,23,6,7,13,1,12,15,3,4,8,16,33,26,18,24,27,
  IRR,IRR,5,25,22,30,10,0,21,14,20,11,9,28,17,IRR,23,6,7,13,
  1,12,15,3,4,8,16,33,26,18,24,27,IRR,IRR,5,25,22,30,10,IRR,
  39,IRR,IRR,IRR,IRR,2,IRR,IRR,IRR,IRR,IRR,IRR,IRR,19,
};

static const PRUint8 BelarusianCompactedLangModel[] =
{
  3,3,3,3,3,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,3,3,3,1,3,0,0,3,0,1,1,0,1,3,
  3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,2,3,3,3,0,3,3,3,1,3,3,3,3,3,1,3,0,0,3,1,0,0,0,0,3,
  3,3,3,3,3,0,3,3,3,3,3,3,2,3,3,3,2,3,3,3,3,3,2,3,3,0,3,3,3,0,3,1,0,3,0,0,1,0,1,3,
  3,3,2,2,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,1,3,3,3,1,3,2,3,3,3,0,1,0,0,3,0,0,0,0,0,1,
  3,3,3,3,3,3,3,3,3,3,3,2,3,3,3,3,3,0,3,1,1,3,3,0,2,3,3,2,0,1,3,0,0,3,0,0,0,0,0,3,
  2,3,3,3,3,1,3,3,3,3,3,3,2,3,3,3,2,3,3,3,3,3,2,3,3,0,3,3,3,1,3,0,0,3,1,1,0,1,0,3,
  3,3,3,3,3,2,2,3,3,3,1,2,3,3,3,2,3,3,3,1,3,2,3,0,2,0,2,3,1,1,1,0,0,2,0,0,0,0,0,2,
  3,3,3,2,3,3,3,3,3,3,3,3,3,3,2,2,3,2,2,0,3,3,3,0,2,3,2,1,2,1,3,0,0,3,0,0,0,0,0,3,
  3,3,2,3,3,3,3,3,2,3,1,1,3,3,3,2,3,1,3,1,2,3,3,1,3,2,2,1,1,1,1,1,1,3,0,0,1,0,0,0,
  3,3,3,3,3,0,3,3,3,3,3,3,3,3,3,3,1,3,3,3,3,3,1,3,3,0,3,3,3,0,3,0,0,3,0,1,0,1,0,1,
  1,3,1,3,3,1,3,3,3,3,3,3,1,3,3,3,1,3,3,3,3,3,1,3,3,0,3,3,3,0,3,0,0,3,0,0,0,0,1,1,
  3,3,2,3,3,3,3,3,3,3,1,3,3,3,3,3,3,3,3,1,3,3,3,0,3,1,2,3,3,0,1,0,0,2,0,0,0,0,0,1,
  2,3,3,3,3,0,3,3,3,3,3,3,2,3,3,3,3,3,3,3,3,3,2,3,3,1,3,3,3,0,3,0,0,3,0,1,0,0,0,1,
  3,3,3,2,3,3,3,3,1,3,3,1,3,3,3,3,3,2,3,1,2,3,3,0,2,1,1,2,1,1,3,1,0,3,0,0,0,0,0,3,
  3,3,3,2,3,3,3,2,2,3,3,1,3,2,1,2,3,1,1,1,1,1,3,0,1,2,0,1,0,1,3,0,0,1,0,0,0,0,0,3,
  3,3,3,3,3,3,3,3,3,3,3,1,3,1,1,2,3,2,3,0,1,2,3,0,2,1,1,3,1,1,1,0,0,1,0,0,0,0,0,2,
  3,3,3,3,3,0,3,3,3,3,3,3,3,3,3,3,1,3,3,3,3,3,3,3,3,1,3,3,3,0,3,0,0,2,0,0,0,0,0,1,
  3,3,3,3,3,3,3,3,1,3,3,3,3,3,3,2,3,2,2,0,3,3,3,0,3,3,0,3,1,1,3,0,0,0,0,0,0,0,0,3,
  3,3,3,1,2,3,3,2,3,3,3,1,3,1,3,1,3,2,3,0,1,2,3,0,0,3,1,1,1,1,3,0,0,1,0,0,0,0,0,3,
  2,3,2,3,3,0,3,3,3,2,3,3,1,3,3,3,1,3,3,0,3,3,2,1,3,0,2,3,3,1,1,0,0,2,0,0,0,0,0,1,
  3,3,3,3,3,2,3,3,3,3,1,3,3,3,3,1,3,1,2,0,3,2,3,1,3,0,1,1,1,1,1,0,0,1,0,0,0,0,0,2,
  3,3,3,3,3,3,3,3,2,3,3,2,3,3,3,1,3,1,2,0,2,1,3,0,2,1,3,3,1,1,3,0,0,1,0,0,0,0,0,2,
  3,3,3,3,3,0,3,3,3,2,3,3,3,3,3,3,1,3,3,3,3,3,1,3,3,0,3,3,3,0,2,0,0,3,0,0,0,0,0,1,
  2,3,1,2,3,1,3,3,3,1,1,3,2,3,3,2,1,3,3,0,3,3,0,0,3,0,2,3,0,0,1,0,0,2,0,0,0,0,0,1,
  3,3,1,1,1,3,3,3,1,3,0,1,3,2,3,1,3,0,2,0,1,3,3,0,3,1,1,1,2,0,0,0,0,1,0,0,0,0,0,1,
  1,3,2,1,3,1,3,2,3,3,3,3,1,3,3,3,0,2,3,0,3,3,1,0,2,0,2,3,1,0,3,0,0,3,0,0,0,0,0,3,
  3,3,3,3,3,1,2,3,3,3,1,2,3,3,3,2,3,1,2,0,2,2,3,0,1,1,2,1,0,1,1,0,0,1,0,0,1,1,1,1,
  3,3,1,2,2,3,3,3,3,2,0,1,3,3,3,2,3,0,3,0,1,1,3,1,3,1,1,2,0,0,1,0,1,1,0,0,0,0,0,0,
  3,3,0,2,3,3,3,2,1,2,0,3,3,1,3,1,3,3,3,1,2,3,3,0,3,1,1,0,3,0,0,0,0,0,0,0,0,0,0,1,
  0,1,1,1,1,0,1,1,1,0,1,1,0,1,0,0,0,1,1,1,1,1,0,1,1,0,1,0,1,3,0,3,3,0,3,3,3,3,3,0,
  2,3,2,3,3,0,3,3,3,2,0,3,1,3,2,2,0,3,3,1,2,3,2,1,3,0,3,2,2,0,3,0,0,1,0,0,0,0,0,0,
  1,0,0,0,1,0,1,1,1,0,0,0,0,1,0,1,0,0,0,1,0,1,1,0,0,0,1,0,1,3,0,3,3,0,3,3,3,3,3,0,
  0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,3,0,3,2,0,2,3,3,3,3,0,
  3,2,3,3,3,2,2,3,3,3,2,1,3,1,1,0,3,1,1,0,2,1,2,0,0,1,0,1,0,1,2,0,0,1,0,0,0,0,0,2,
  0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,3,0,2,3,0,3,3,3,3,3,0,
  1,0,1,0,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,3,0,3,3,0,3,3,3,3,3,0,
  1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,3,0,3,3,0,3,2,3,3,3,0,
  1,0,1,1,0,0,1,0,0,0,0,0,1,1,0,1,1,0,0,0,0,0,0,0,1,0,0,0,1,3,0,3,3,0,3,2,2,3,3,0,
  1,0,0,0,0,0,0,1,0,1,0,1,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,3,0,3,3,0,3,3,2,3,3,0,
  1,3,0,3,3,0,3,3,3,1,1,3,0,3,3,2,0,3,2,3,3,1,1,3,1,0,2,1,1,0,2,0,0,2,0,0,0,0,0,1,
};


const SequenceModel Windows_1251BelarusianModel =
{
  Windows_1251_CharToOrderMap,
  BelarusianCompactedLangModel,
  BelarusianOrderWidth,
  0.9990006073592278f,
  PR_FALSE,
  "WINDOWS-1251",
  "be"
};

const SequenceModel Iso_8859_5BelarusianModel =
{
  Iso_8859_5_CharToOrderMap,
  BelarusianCompactedLangModel,
  BelarusianOrderWidth,
  0.9990006073592278f,
  PR_FALSE,
  "ISO-8859-5",
  "be"
};

const LanguageModel BelarusianModel =
{
  "be",
  Unicode_CharOrder,
  Unicode_Char_size,

  BelarusianFCMLowerBound,
  BelarusianFCMUpperBound,
  BelarusianUnicodeCharToOrderIsReduced,
  BelarusianUnicodeCharToOrder,
  BelarusianUnicodeCharToOrderFirstTableChunkSize,
  BelarusianUnicodeCharToOrderSecondTableChunkOffset,
  BelarusianUnicodeCharToOrderSecondTableChunkSize,
  BelarusianUnicodeCharToOrder2,
  OrderToRatio,
  BelarusianCompactedLangModel,
  BelarusianOrderWidth,
  6,
  0.4129129930516004f,
  31,
  0.03056871789585175f,
  0.9782318734407166f,
};
